/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the UserVoiceStreamSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserVoiceStreamSummary{}

// UserVoiceStreamSummary struct for UserVoiceStreamSummary
type UserVoiceStreamSummary struct {
	AudioMode   *string `json:"audio_mode,omitempty"`
	ChannelId   *int32  `json:"channel_id,omitempty"`
	Id          *int32  `json:"id,omitempty"`
	OwnerUserId *int32  `json:"owner_user_id,omitempty"`
	SourceType  *string `json:"source_type,omitempty"`
	StartedAt   *int32  `json:"started_at,omitempty"`
}

// NewUserVoiceStreamSummary instantiates a new UserVoiceStreamSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserVoiceStreamSummary() *UserVoiceStreamSummary {
	this := UserVoiceStreamSummary{}
	return &this
}

// NewUserVoiceStreamSummaryWithDefaults instantiates a new UserVoiceStreamSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserVoiceStreamSummaryWithDefaults() *UserVoiceStreamSummary {
	this := UserVoiceStreamSummary{}
	return &this
}

// GetAudioMode returns the AudioMode field value if set, zero value otherwise.
func (o *UserVoiceStreamSummary) GetAudioMode() string {
	if o == nil || IsNil(o.AudioMode) {
		var ret string
		return ret
	}
	return *o.AudioMode
}

// GetAudioModeOk returns a tuple with the AudioMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserVoiceStreamSummary) GetAudioModeOk() (*string, bool) {
	if o == nil || IsNil(o.AudioMode) {
		return nil, false
	}
	return o.AudioMode, true
}

// HasAudioMode returns a boolean if a field has been set.
func (o *UserVoiceStreamSummary) HasAudioMode() bool {
	if o != nil && !IsNil(o.AudioMode) {
		return true
	}

	return false
}

// SetAudioMode gets a reference to the given string and assigns it to the AudioMode field.
func (o *UserVoiceStreamSummary) SetAudioMode(v string) {
	o.AudioMode = &v
}

// GetChannelId returns the ChannelId field value if set, zero value otherwise.
func (o *UserVoiceStreamSummary) GetChannelId() int32 {
	if o == nil || IsNil(o.ChannelId) {
		var ret int32
		return ret
	}
	return *o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserVoiceStreamSummary) GetChannelIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ChannelId) {
		return nil, false
	}
	return o.ChannelId, true
}

// HasChannelId returns a boolean if a field has been set.
func (o *UserVoiceStreamSummary) HasChannelId() bool {
	if o != nil && !IsNil(o.ChannelId) {
		return true
	}

	return false
}

// SetChannelId gets a reference to the given int32 and assigns it to the ChannelId field.
func (o *UserVoiceStreamSummary) SetChannelId(v int32) {
	o.ChannelId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UserVoiceStreamSummary) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserVoiceStreamSummary) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UserVoiceStreamSummary) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *UserVoiceStreamSummary) SetId(v int32) {
	o.Id = &v
}

// GetOwnerUserId returns the OwnerUserId field value if set, zero value otherwise.
func (o *UserVoiceStreamSummary) GetOwnerUserId() int32 {
	if o == nil || IsNil(o.OwnerUserId) {
		var ret int32
		return ret
	}
	return *o.OwnerUserId
}

// GetOwnerUserIdOk returns a tuple with the OwnerUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserVoiceStreamSummary) GetOwnerUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OwnerUserId) {
		return nil, false
	}
	return o.OwnerUserId, true
}

// HasOwnerUserId returns a boolean if a field has been set.
func (o *UserVoiceStreamSummary) HasOwnerUserId() bool {
	if o != nil && !IsNil(o.OwnerUserId) {
		return true
	}

	return false
}

// SetOwnerUserId gets a reference to the given int32 and assigns it to the OwnerUserId field.
func (o *UserVoiceStreamSummary) SetOwnerUserId(v int32) {
	o.OwnerUserId = &v
}

// GetSourceType returns the SourceType field value if set, zero value otherwise.
func (o *UserVoiceStreamSummary) GetSourceType() string {
	if o == nil || IsNil(o.SourceType) {
		var ret string
		return ret
	}
	return *o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserVoiceStreamSummary) GetSourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SourceType) {
		return nil, false
	}
	return o.SourceType, true
}

// HasSourceType returns a boolean if a field has been set.
func (o *UserVoiceStreamSummary) HasSourceType() bool {
	if o != nil && !IsNil(o.SourceType) {
		return true
	}

	return false
}

// SetSourceType gets a reference to the given string and assigns it to the SourceType field.
func (o *UserVoiceStreamSummary) SetSourceType(v string) {
	o.SourceType = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *UserVoiceStreamSummary) GetStartedAt() int32 {
	if o == nil || IsNil(o.StartedAt) {
		var ret int32
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserVoiceStreamSummary) GetStartedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *UserVoiceStreamSummary) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given int32 and assigns it to the StartedAt field.
func (o *UserVoiceStreamSummary) SetStartedAt(v int32) {
	o.StartedAt = &v
}

func (o UserVoiceStreamSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserVoiceStreamSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AudioMode) {
		toSerialize["audio_mode"] = o.AudioMode
	}
	if !IsNil(o.ChannelId) {
		toSerialize["channel_id"] = o.ChannelId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OwnerUserId) {
		toSerialize["owner_user_id"] = o.OwnerUserId
	}
	if !IsNil(o.SourceType) {
		toSerialize["source_type"] = o.SourceType
	}
	if !IsNil(o.StartedAt) {
		toSerialize["started_at"] = o.StartedAt
	}
	return toSerialize, nil
}

type NullableUserVoiceStreamSummary struct {
	value *UserVoiceStreamSummary
	isSet bool
}

func (v NullableUserVoiceStreamSummary) Get() *UserVoiceStreamSummary {
	return v.value
}

func (v *NullableUserVoiceStreamSummary) Set(val *UserVoiceStreamSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableUserVoiceStreamSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableUserVoiceStreamSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserVoiceStreamSummary(val *UserVoiceStreamSummary) *NullableUserVoiceStreamSummary {
	return &NullableUserVoiceStreamSummary{value: val, isSet: true}
}

func (v NullableUserVoiceStreamSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserVoiceStreamSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
