/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the GuildCreateGuildRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuildCreateGuildRequest{}

// GuildCreateGuildRequest struct for GuildCreateGuildRequest
type GuildCreateGuildRequest struct {
	// Icon ID
	IconId *int32 `json:"icon_id,omitempty"`
	// Guild name
	Name *string `json:"name,omitempty"`
	// Whether the guild is public
	Public *bool `json:"public,omitempty"`
}

// NewGuildCreateGuildRequest instantiates a new GuildCreateGuildRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuildCreateGuildRequest() *GuildCreateGuildRequest {
	this := GuildCreateGuildRequest{}
	var public bool = false
	this.Public = &public
	return &this
}

// NewGuildCreateGuildRequestWithDefaults instantiates a new GuildCreateGuildRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuildCreateGuildRequestWithDefaults() *GuildCreateGuildRequest {
	this := GuildCreateGuildRequest{}
	var public bool = false
	this.Public = &public
	return &this
}

// GetIconId returns the IconId field value if set, zero value otherwise.
func (o *GuildCreateGuildRequest) GetIconId() int32 {
	if o == nil || IsNil(o.IconId) {
		var ret int32
		return ret
	}
	return *o.IconId
}

// GetIconIdOk returns a tuple with the IconId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildCreateGuildRequest) GetIconIdOk() (*int32, bool) {
	if o == nil || IsNil(o.IconId) {
		return nil, false
	}
	return o.IconId, true
}

// HasIconId returns a boolean if a field has been set.
func (o *GuildCreateGuildRequest) HasIconId() bool {
	if o != nil && !IsNil(o.IconId) {
		return true
	}

	return false
}

// SetIconId gets a reference to the given int32 and assigns it to the IconId field.
func (o *GuildCreateGuildRequest) SetIconId(v int32) {
	o.IconId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GuildCreateGuildRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildCreateGuildRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GuildCreateGuildRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GuildCreateGuildRequest) SetName(v string) {
	o.Name = &v
}

// GetPublic returns the Public field value if set, zero value otherwise.
func (o *GuildCreateGuildRequest) GetPublic() bool {
	if o == nil || IsNil(o.Public) {
		var ret bool
		return ret
	}
	return *o.Public
}

// GetPublicOk returns a tuple with the Public field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildCreateGuildRequest) GetPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.Public) {
		return nil, false
	}
	return o.Public, true
}

// HasPublic returns a boolean if a field has been set.
func (o *GuildCreateGuildRequest) HasPublic() bool {
	if o != nil && !IsNil(o.Public) {
		return true
	}

	return false
}

// SetPublic gets a reference to the given bool and assigns it to the Public field.
func (o *GuildCreateGuildRequest) SetPublic(v bool) {
	o.Public = &v
}

func (o GuildCreateGuildRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuildCreateGuildRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IconId) {
		toSerialize["icon_id"] = o.IconId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Public) {
		toSerialize["public"] = o.Public
	}
	return toSerialize, nil
}

type NullableGuildCreateGuildRequest struct {
	value *GuildCreateGuildRequest
	isSet bool
}

func (v NullableGuildCreateGuildRequest) Get() *GuildCreateGuildRequest {
	return v.value
}

func (v *NullableGuildCreateGuildRequest) Set(val *GuildCreateGuildRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGuildCreateGuildRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGuildCreateGuildRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuildCreateGuildRequest(val *GuildCreateGuildRequest) *NullableGuildCreateGuildRequest {
	return &NullableGuildCreateGuildRequest{value: val, isSet: true}
}

func (v NullableGuildCreateGuildRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuildCreateGuildRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
