/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the DeveloperBotAuthorizationPreview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeveloperBotAuthorizationPreview{}

// DeveloperBotAuthorizationPreview struct for DeveloperBotAuthorizationPreview
type DeveloperBotAuthorizationPreview struct {
	Bot                  *DeveloperBotResponse `json:"bot,omitempty"`
	GrantId              *int32                `json:"grant_id,omitempty"`
	RequestedPermissions *int32                `json:"requested_permissions,omitempty"`
}

// NewDeveloperBotAuthorizationPreview instantiates a new DeveloperBotAuthorizationPreview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeveloperBotAuthorizationPreview() *DeveloperBotAuthorizationPreview {
	this := DeveloperBotAuthorizationPreview{}
	return &this
}

// NewDeveloperBotAuthorizationPreviewWithDefaults instantiates a new DeveloperBotAuthorizationPreview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeveloperBotAuthorizationPreviewWithDefaults() *DeveloperBotAuthorizationPreview {
	this := DeveloperBotAuthorizationPreview{}
	return &this
}

// GetBot returns the Bot field value if set, zero value otherwise.
func (o *DeveloperBotAuthorizationPreview) GetBot() DeveloperBotResponse {
	if o == nil || IsNil(o.Bot) {
		var ret DeveloperBotResponse
		return ret
	}
	return *o.Bot
}

// GetBotOk returns a tuple with the Bot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeveloperBotAuthorizationPreview) GetBotOk() (*DeveloperBotResponse, bool) {
	if o == nil || IsNil(o.Bot) {
		return nil, false
	}
	return o.Bot, true
}

// HasBot returns a boolean if a field has been set.
func (o *DeveloperBotAuthorizationPreview) HasBot() bool {
	if o != nil && !IsNil(o.Bot) {
		return true
	}

	return false
}

// SetBot gets a reference to the given DeveloperBotResponse and assigns it to the Bot field.
func (o *DeveloperBotAuthorizationPreview) SetBot(v DeveloperBotResponse) {
	o.Bot = &v
}

// GetGrantId returns the GrantId field value if set, zero value otherwise.
func (o *DeveloperBotAuthorizationPreview) GetGrantId() int32 {
	if o == nil || IsNil(o.GrantId) {
		var ret int32
		return ret
	}
	return *o.GrantId
}

// GetGrantIdOk returns a tuple with the GrantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeveloperBotAuthorizationPreview) GetGrantIdOk() (*int32, bool) {
	if o == nil || IsNil(o.GrantId) {
		return nil, false
	}
	return o.GrantId, true
}

// HasGrantId returns a boolean if a field has been set.
func (o *DeveloperBotAuthorizationPreview) HasGrantId() bool {
	if o != nil && !IsNil(o.GrantId) {
		return true
	}

	return false
}

// SetGrantId gets a reference to the given int32 and assigns it to the GrantId field.
func (o *DeveloperBotAuthorizationPreview) SetGrantId(v int32) {
	o.GrantId = &v
}

// GetRequestedPermissions returns the RequestedPermissions field value if set, zero value otherwise.
func (o *DeveloperBotAuthorizationPreview) GetRequestedPermissions() int32 {
	if o == nil || IsNil(o.RequestedPermissions) {
		var ret int32
		return ret
	}
	return *o.RequestedPermissions
}

// GetRequestedPermissionsOk returns a tuple with the RequestedPermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeveloperBotAuthorizationPreview) GetRequestedPermissionsOk() (*int32, bool) {
	if o == nil || IsNil(o.RequestedPermissions) {
		return nil, false
	}
	return o.RequestedPermissions, true
}

// HasRequestedPermissions returns a boolean if a field has been set.
func (o *DeveloperBotAuthorizationPreview) HasRequestedPermissions() bool {
	if o != nil && !IsNil(o.RequestedPermissions) {
		return true
	}

	return false
}

// SetRequestedPermissions gets a reference to the given int32 and assigns it to the RequestedPermissions field.
func (o *DeveloperBotAuthorizationPreview) SetRequestedPermissions(v int32) {
	o.RequestedPermissions = &v
}

func (o DeveloperBotAuthorizationPreview) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeveloperBotAuthorizationPreview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Bot) {
		toSerialize["bot"] = o.Bot
	}
	if !IsNil(o.GrantId) {
		toSerialize["grant_id"] = o.GrantId
	}
	if !IsNil(o.RequestedPermissions) {
		toSerialize["requested_permissions"] = o.RequestedPermissions
	}
	return toSerialize, nil
}

type NullableDeveloperBotAuthorizationPreview struct {
	value *DeveloperBotAuthorizationPreview
	isSet bool
}

func (v NullableDeveloperBotAuthorizationPreview) Get() *DeveloperBotAuthorizationPreview {
	return v.value
}

func (v *NullableDeveloperBotAuthorizationPreview) Set(val *DeveloperBotAuthorizationPreview) {
	v.value = val
	v.isSet = true
}

func (v NullableDeveloperBotAuthorizationPreview) IsSet() bool {
	return v.isSet
}

func (v *NullableDeveloperBotAuthorizationPreview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeveloperBotAuthorizationPreview(val *DeveloperBotAuthorizationPreview) *NullableDeveloperBotAuthorizationPreview {
	return &NullableDeveloperBotAuthorizationPreview{value: val, isSet: true}
}

func (v NullableDeveloperBotAuthorizationPreview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeveloperBotAuthorizationPreview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
