/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the ModelUserUISounds type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelUserUISounds{}

// ModelUserUISounds struct for ModelUserUISounds
type ModelUserUISounds struct {
	Deafen       *bool `json:"deafen,omitempty"`
	Mute         *bool `json:"mute,omitempty"`
	Notification *bool `json:"notification,omitempty"`
	VoiceChannel *bool `json:"voice_channel,omitempty"`
}

// NewModelUserUISounds instantiates a new ModelUserUISounds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelUserUISounds() *ModelUserUISounds {
	this := ModelUserUISounds{}
	return &this
}

// NewModelUserUISoundsWithDefaults instantiates a new ModelUserUISounds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelUserUISoundsWithDefaults() *ModelUserUISounds {
	this := ModelUserUISounds{}
	return &this
}

// GetDeafen returns the Deafen field value if set, zero value otherwise.
func (o *ModelUserUISounds) GetDeafen() bool {
	if o == nil || IsNil(o.Deafen) {
		var ret bool
		return ret
	}
	return *o.Deafen
}

// GetDeafenOk returns a tuple with the Deafen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserUISounds) GetDeafenOk() (*bool, bool) {
	if o == nil || IsNil(o.Deafen) {
		return nil, false
	}
	return o.Deafen, true
}

// HasDeafen returns a boolean if a field has been set.
func (o *ModelUserUISounds) HasDeafen() bool {
	if o != nil && !IsNil(o.Deafen) {
		return true
	}

	return false
}

// SetDeafen gets a reference to the given bool and assigns it to the Deafen field.
func (o *ModelUserUISounds) SetDeafen(v bool) {
	o.Deafen = &v
}

// GetMute returns the Mute field value if set, zero value otherwise.
func (o *ModelUserUISounds) GetMute() bool {
	if o == nil || IsNil(o.Mute) {
		var ret bool
		return ret
	}
	return *o.Mute
}

// GetMuteOk returns a tuple with the Mute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserUISounds) GetMuteOk() (*bool, bool) {
	if o == nil || IsNil(o.Mute) {
		return nil, false
	}
	return o.Mute, true
}

// HasMute returns a boolean if a field has been set.
func (o *ModelUserUISounds) HasMute() bool {
	if o != nil && !IsNil(o.Mute) {
		return true
	}

	return false
}

// SetMute gets a reference to the given bool and assigns it to the Mute field.
func (o *ModelUserUISounds) SetMute(v bool) {
	o.Mute = &v
}

// GetNotification returns the Notification field value if set, zero value otherwise.
func (o *ModelUserUISounds) GetNotification() bool {
	if o == nil || IsNil(o.Notification) {
		var ret bool
		return ret
	}
	return *o.Notification
}

// GetNotificationOk returns a tuple with the Notification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserUISounds) GetNotificationOk() (*bool, bool) {
	if o == nil || IsNil(o.Notification) {
		return nil, false
	}
	return o.Notification, true
}

// HasNotification returns a boolean if a field has been set.
func (o *ModelUserUISounds) HasNotification() bool {
	if o != nil && !IsNil(o.Notification) {
		return true
	}

	return false
}

// SetNotification gets a reference to the given bool and assigns it to the Notification field.
func (o *ModelUserUISounds) SetNotification(v bool) {
	o.Notification = &v
}

// GetVoiceChannel returns the VoiceChannel field value if set, zero value otherwise.
func (o *ModelUserUISounds) GetVoiceChannel() bool {
	if o == nil || IsNil(o.VoiceChannel) {
		var ret bool
		return ret
	}
	return *o.VoiceChannel
}

// GetVoiceChannelOk returns a tuple with the VoiceChannel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserUISounds) GetVoiceChannelOk() (*bool, bool) {
	if o == nil || IsNil(o.VoiceChannel) {
		return nil, false
	}
	return o.VoiceChannel, true
}

// HasVoiceChannel returns a boolean if a field has been set.
func (o *ModelUserUISounds) HasVoiceChannel() bool {
	if o != nil && !IsNil(o.VoiceChannel) {
		return true
	}

	return false
}

// SetVoiceChannel gets a reference to the given bool and assigns it to the VoiceChannel field.
func (o *ModelUserUISounds) SetVoiceChannel(v bool) {
	o.VoiceChannel = &v
}

func (o ModelUserUISounds) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelUserUISounds) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deafen) {
		toSerialize["deafen"] = o.Deafen
	}
	if !IsNil(o.Mute) {
		toSerialize["mute"] = o.Mute
	}
	if !IsNil(o.Notification) {
		toSerialize["notification"] = o.Notification
	}
	if !IsNil(o.VoiceChannel) {
		toSerialize["voice_channel"] = o.VoiceChannel
	}
	return toSerialize, nil
}

type NullableModelUserUISounds struct {
	value *ModelUserUISounds
	isSet bool
}

func (v NullableModelUserUISounds) Get() *ModelUserUISounds {
	return v.value
}

func (v *NullableModelUserUISounds) Set(val *ModelUserUISounds) {
	v.value = val
	v.isSet = true
}

func (v NullableModelUserUISounds) IsSet() bool {
	return v.isSet
}

func (v *NullableModelUserUISounds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelUserUISounds(val *ModelUserUISounds) *NullableModelUserUISounds {
	return &NullableModelUserUISounds{value: val, isSet: true}
}

func (v NullableModelUserUISounds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelUserUISounds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
