/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the DtoAvatarUpload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoAvatarUpload{}

// DtoAvatarUpload struct for DtoAvatarUpload
type DtoAvatarUpload struct {
	Id     *int32 `json:"id,omitempty"`
	UserId *int32 `json:"user_id,omitempty"`
}

// NewDtoAvatarUpload instantiates a new DtoAvatarUpload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoAvatarUpload() *DtoAvatarUpload {
	this := DtoAvatarUpload{}
	return &this
}

// NewDtoAvatarUploadWithDefaults instantiates a new DtoAvatarUpload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoAvatarUploadWithDefaults() *DtoAvatarUpload {
	this := DtoAvatarUpload{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DtoAvatarUpload) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoAvatarUpload) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DtoAvatarUpload) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *DtoAvatarUpload) SetId(v int32) {
	o.Id = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *DtoAvatarUpload) GetUserId() int32 {
	if o == nil || IsNil(o.UserId) {
		var ret int32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoAvatarUpload) GetUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *DtoAvatarUpload) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int32 and assigns it to the UserId field.
func (o *DtoAvatarUpload) SetUserId(v int32) {
	o.UserId = &v
}

func (o DtoAvatarUpload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoAvatarUpload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	return toSerialize, nil
}

type NullableDtoAvatarUpload struct {
	value *DtoAvatarUpload
	isSet bool
}

func (v NullableDtoAvatarUpload) Get() *DtoAvatarUpload {
	return v.value
}

func (v *NullableDtoAvatarUpload) Set(val *DtoAvatarUpload) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoAvatarUpload) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoAvatarUpload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoAvatarUpload(val *DtoAvatarUpload) *NullableDtoAvatarUpload {
	return &NullableDtoAvatarUpload{value: val, isSet: true}
}

func (v NullableDtoAvatarUpload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoAvatarUpload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
