/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the GuildSetVoiceRegionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuildSetVoiceRegionRequest{}

// GuildSetVoiceRegionRequest struct for GuildSetVoiceRegionRequest
type GuildSetVoiceRegionRequest struct {
	Region *string `json:"region,omitempty"`
}

// NewGuildSetVoiceRegionRequest instantiates a new GuildSetVoiceRegionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuildSetVoiceRegionRequest() *GuildSetVoiceRegionRequest {
	this := GuildSetVoiceRegionRequest{}
	return &this
}

// NewGuildSetVoiceRegionRequestWithDefaults instantiates a new GuildSetVoiceRegionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuildSetVoiceRegionRequestWithDefaults() *GuildSetVoiceRegionRequest {
	this := GuildSetVoiceRegionRequest{}
	return &this
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *GuildSetVoiceRegionRequest) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildSetVoiceRegionRequest) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *GuildSetVoiceRegionRequest) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *GuildSetVoiceRegionRequest) SetRegion(v string) {
	o.Region = &v
}

func (o GuildSetVoiceRegionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuildSetVoiceRegionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	return toSerialize, nil
}

type NullableGuildSetVoiceRegionRequest struct {
	value *GuildSetVoiceRegionRequest
	isSet bool
}

func (v NullableGuildSetVoiceRegionRequest) Get() *GuildSetVoiceRegionRequest {
	return v.value
}

func (v *NullableGuildSetVoiceRegionRequest) Set(val *GuildSetVoiceRegionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGuildSetVoiceRegionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGuildSetVoiceRegionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuildSetVoiceRegionRequest(val *GuildSetVoiceRegionRequest) *NullableGuildSetVoiceRegionRequest {
	return &NullableGuildSetVoiceRegionRequest{value: val, isSet: true}
}

func (v NullableGuildSetVoiceRegionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuildSetVoiceRegionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
