/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the AuthDisableTwoFactorRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthDisableTwoFactorRequest{}

// AuthDisableTwoFactorRequest struct for AuthDisableTwoFactorRequest
type AuthDisableTwoFactorRequest struct {
	Code            *string `json:"code,omitempty"`
	CodeType        *string `json:"code_type,omitempty"`
	CurrentPassword *string `json:"current_password,omitempty"`
}

// NewAuthDisableTwoFactorRequest instantiates a new AuthDisableTwoFactorRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthDisableTwoFactorRequest() *AuthDisableTwoFactorRequest {
	this := AuthDisableTwoFactorRequest{}
	return &this
}

// NewAuthDisableTwoFactorRequestWithDefaults instantiates a new AuthDisableTwoFactorRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthDisableTwoFactorRequestWithDefaults() *AuthDisableTwoFactorRequest {
	this := AuthDisableTwoFactorRequest{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *AuthDisableTwoFactorRequest) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthDisableTwoFactorRequest) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *AuthDisableTwoFactorRequest) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *AuthDisableTwoFactorRequest) SetCode(v string) {
	o.Code = &v
}

// GetCodeType returns the CodeType field value if set, zero value otherwise.
func (o *AuthDisableTwoFactorRequest) GetCodeType() string {
	if o == nil || IsNil(o.CodeType) {
		var ret string
		return ret
	}
	return *o.CodeType
}

// GetCodeTypeOk returns a tuple with the CodeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthDisableTwoFactorRequest) GetCodeTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CodeType) {
		return nil, false
	}
	return o.CodeType, true
}

// HasCodeType returns a boolean if a field has been set.
func (o *AuthDisableTwoFactorRequest) HasCodeType() bool {
	if o != nil && !IsNil(o.CodeType) {
		return true
	}

	return false
}

// SetCodeType gets a reference to the given string and assigns it to the CodeType field.
func (o *AuthDisableTwoFactorRequest) SetCodeType(v string) {
	o.CodeType = &v
}

// GetCurrentPassword returns the CurrentPassword field value if set, zero value otherwise.
func (o *AuthDisableTwoFactorRequest) GetCurrentPassword() string {
	if o == nil || IsNil(o.CurrentPassword) {
		var ret string
		return ret
	}
	return *o.CurrentPassword
}

// GetCurrentPasswordOk returns a tuple with the CurrentPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthDisableTwoFactorRequest) GetCurrentPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentPassword) {
		return nil, false
	}
	return o.CurrentPassword, true
}

// HasCurrentPassword returns a boolean if a field has been set.
func (o *AuthDisableTwoFactorRequest) HasCurrentPassword() bool {
	if o != nil && !IsNil(o.CurrentPassword) {
		return true
	}

	return false
}

// SetCurrentPassword gets a reference to the given string and assigns it to the CurrentPassword field.
func (o *AuthDisableTwoFactorRequest) SetCurrentPassword(v string) {
	o.CurrentPassword = &v
}

func (o AuthDisableTwoFactorRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthDisableTwoFactorRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.CodeType) {
		toSerialize["code_type"] = o.CodeType
	}
	if !IsNil(o.CurrentPassword) {
		toSerialize["current_password"] = o.CurrentPassword
	}
	return toSerialize, nil
}

type NullableAuthDisableTwoFactorRequest struct {
	value *AuthDisableTwoFactorRequest
	isSet bool
}

func (v NullableAuthDisableTwoFactorRequest) Get() *AuthDisableTwoFactorRequest {
	return v.value
}

func (v *NullableAuthDisableTwoFactorRequest) Set(val *AuthDisableTwoFactorRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthDisableTwoFactorRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthDisableTwoFactorRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthDisableTwoFactorRequest(val *AuthDisableTwoFactorRequest) *NullableAuthDisableTwoFactorRequest {
	return &NullableAuthDisableTwoFactorRequest{value: val, isSet: true}
}

func (v NullableAuthDisableTwoFactorRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthDisableTwoFactorRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
