/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the UserCreateBannerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCreateBannerRequest{}

// UserCreateBannerRequest struct for UserCreateBannerRequest
type UserCreateBannerRequest struct {
	ContentType *string `json:"content_type,omitempty"`
	FileSize    *int32  `json:"file_size,omitempty"`
}

// NewUserCreateBannerRequest instantiates a new UserCreateBannerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCreateBannerRequest() *UserCreateBannerRequest {
	this := UserCreateBannerRequest{}
	return &this
}

// NewUserCreateBannerRequestWithDefaults instantiates a new UserCreateBannerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCreateBannerRequestWithDefaults() *UserCreateBannerRequest {
	this := UserCreateBannerRequest{}
	return &this
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *UserCreateBannerRequest) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateBannerRequest) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *UserCreateBannerRequest) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *UserCreateBannerRequest) SetContentType(v string) {
	o.ContentType = &v
}

// GetFileSize returns the FileSize field value if set, zero value otherwise.
func (o *UserCreateBannerRequest) GetFileSize() int32 {
	if o == nil || IsNil(o.FileSize) {
		var ret int32
		return ret
	}
	return *o.FileSize
}

// GetFileSizeOk returns a tuple with the FileSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateBannerRequest) GetFileSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.FileSize) {
		return nil, false
	}
	return o.FileSize, true
}

// HasFileSize returns a boolean if a field has been set.
func (o *UserCreateBannerRequest) HasFileSize() bool {
	if o != nil && !IsNil(o.FileSize) {
		return true
	}

	return false
}

// SetFileSize gets a reference to the given int32 and assigns it to the FileSize field.
func (o *UserCreateBannerRequest) SetFileSize(v int32) {
	o.FileSize = &v
}

func (o UserCreateBannerRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCreateBannerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContentType) {
		toSerialize["content_type"] = o.ContentType
	}
	if !IsNil(o.FileSize) {
		toSerialize["file_size"] = o.FileSize
	}
	return toSerialize, nil
}

type NullableUserCreateBannerRequest struct {
	value *UserCreateBannerRequest
	isSet bool
}

func (v NullableUserCreateBannerRequest) Get() *UserCreateBannerRequest {
	return v.value
}

func (v *NullableUserCreateBannerRequest) Set(val *UserCreateBannerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCreateBannerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCreateBannerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCreateBannerRequest(val *UserCreateBannerRequest) *NullableUserCreateBannerRequest {
	return &NullableUserCreateBannerRequest{value: val, isSet: true}
}

func (v NullableUserCreateBannerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCreateBannerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
