/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
	"fmt"
)

// ModelNotificationsType the model 'ModelNotificationsType'
type ModelNotificationsType int32

// List of model.NotificationsType
const (
	NotificationsAll      ModelNotificationsType = 0
	NotificationsMentions ModelNotificationsType = 1
	NotificationsNone     ModelNotificationsType = 2
)

// All allowed values of ModelNotificationsType enum
var AllowedModelNotificationsTypeEnumValues = []ModelNotificationsType{
	0,
	1,
	2,
}

func (v *ModelNotificationsType) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ModelNotificationsType(value)
	for _, existing := range AllowedModelNotificationsTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ModelNotificationsType", value)
}

// NewModelNotificationsTypeFromValue returns a pointer to a valid ModelNotificationsType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewModelNotificationsTypeFromValue(v int32) (*ModelNotificationsType, error) {
	ev := ModelNotificationsType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ModelNotificationsType: valid values are %v", v, AllowedModelNotificationsTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ModelNotificationsType) IsValid() bool {
	for _, existing := range AllowedModelNotificationsTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to model.NotificationsType value
func (v ModelNotificationsType) Ptr() *ModelNotificationsType {
	return &v
}

type NullableModelNotificationsType struct {
	value *ModelNotificationsType
	isSet bool
}

func (v NullableModelNotificationsType) Get() *ModelNotificationsType {
	return v.value
}

func (v *NullableModelNotificationsType) Set(val *ModelNotificationsType) {
	v.value = val
	v.isSet = true
}

func (v NullableModelNotificationsType) IsSet() bool {
	return v.isSet
}

func (v *NullableModelNotificationsType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelNotificationsType(val *ModelNotificationsType) *NullableModelNotificationsType {
	return &NullableModelNotificationsType{value: val, isSet: true}
}

func (v NullableModelNotificationsType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelNotificationsType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
