/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the ModelBotInstallGrant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelBotInstallGrant{}

// ModelBotInstallGrant struct for ModelBotInstallGrant
type ModelBotInstallGrant struct {
	BotUserId            *int32  `json:"bot_user_id,omitempty"`
	CreatedAt            *string `json:"created_at,omitempty"`
	ExpiresAt            *string `json:"expires_at,omitempty"`
	Id                   *int32  `json:"id,omitempty"`
	MaxUses              *int32  `json:"max_uses,omitempty"`
	OwnerUserId          *int32  `json:"owner_user_id,omitempty"`
	RequestedPermissions *int32  `json:"requested_permissions,omitempty"`
	RevokedAt            *string `json:"revoked_at,omitempty"`
	TokenPrefix          *string `json:"token_prefix,omitempty"`
	Uses                 *int32  `json:"uses,omitempty"`
}

// NewModelBotInstallGrant instantiates a new ModelBotInstallGrant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelBotInstallGrant() *ModelBotInstallGrant {
	this := ModelBotInstallGrant{}
	return &this
}

// NewModelBotInstallGrantWithDefaults instantiates a new ModelBotInstallGrant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelBotInstallGrantWithDefaults() *ModelBotInstallGrant {
	this := ModelBotInstallGrant{}
	return &this
}

// GetBotUserId returns the BotUserId field value if set, zero value otherwise.
func (o *ModelBotInstallGrant) GetBotUserId() int32 {
	if o == nil || IsNil(o.BotUserId) {
		var ret int32
		return ret
	}
	return *o.BotUserId
}

// GetBotUserIdOk returns a tuple with the BotUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotInstallGrant) GetBotUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.BotUserId) {
		return nil, false
	}
	return o.BotUserId, true
}

// HasBotUserId returns a boolean if a field has been set.
func (o *ModelBotInstallGrant) HasBotUserId() bool {
	if o != nil && !IsNil(o.BotUserId) {
		return true
	}

	return false
}

// SetBotUserId gets a reference to the given int32 and assigns it to the BotUserId field.
func (o *ModelBotInstallGrant) SetBotUserId(v int32) {
	o.BotUserId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ModelBotInstallGrant) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotInstallGrant) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ModelBotInstallGrant) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ModelBotInstallGrant) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *ModelBotInstallGrant) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret string
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotInstallGrant) GetExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *ModelBotInstallGrant) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given string and assigns it to the ExpiresAt field.
func (o *ModelBotInstallGrant) SetExpiresAt(v string) {
	o.ExpiresAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelBotInstallGrant) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotInstallGrant) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelBotInstallGrant) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ModelBotInstallGrant) SetId(v int32) {
	o.Id = &v
}

// GetMaxUses returns the MaxUses field value if set, zero value otherwise.
func (o *ModelBotInstallGrant) GetMaxUses() int32 {
	if o == nil || IsNil(o.MaxUses) {
		var ret int32
		return ret
	}
	return *o.MaxUses
}

// GetMaxUsesOk returns a tuple with the MaxUses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotInstallGrant) GetMaxUsesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxUses) {
		return nil, false
	}
	return o.MaxUses, true
}

// HasMaxUses returns a boolean if a field has been set.
func (o *ModelBotInstallGrant) HasMaxUses() bool {
	if o != nil && !IsNil(o.MaxUses) {
		return true
	}

	return false
}

// SetMaxUses gets a reference to the given int32 and assigns it to the MaxUses field.
func (o *ModelBotInstallGrant) SetMaxUses(v int32) {
	o.MaxUses = &v
}

// GetOwnerUserId returns the OwnerUserId field value if set, zero value otherwise.
func (o *ModelBotInstallGrant) GetOwnerUserId() int32 {
	if o == nil || IsNil(o.OwnerUserId) {
		var ret int32
		return ret
	}
	return *o.OwnerUserId
}

// GetOwnerUserIdOk returns a tuple with the OwnerUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotInstallGrant) GetOwnerUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OwnerUserId) {
		return nil, false
	}
	return o.OwnerUserId, true
}

// HasOwnerUserId returns a boolean if a field has been set.
func (o *ModelBotInstallGrant) HasOwnerUserId() bool {
	if o != nil && !IsNil(o.OwnerUserId) {
		return true
	}

	return false
}

// SetOwnerUserId gets a reference to the given int32 and assigns it to the OwnerUserId field.
func (o *ModelBotInstallGrant) SetOwnerUserId(v int32) {
	o.OwnerUserId = &v
}

// GetRequestedPermissions returns the RequestedPermissions field value if set, zero value otherwise.
func (o *ModelBotInstallGrant) GetRequestedPermissions() int32 {
	if o == nil || IsNil(o.RequestedPermissions) {
		var ret int32
		return ret
	}
	return *o.RequestedPermissions
}

// GetRequestedPermissionsOk returns a tuple with the RequestedPermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotInstallGrant) GetRequestedPermissionsOk() (*int32, bool) {
	if o == nil || IsNil(o.RequestedPermissions) {
		return nil, false
	}
	return o.RequestedPermissions, true
}

// HasRequestedPermissions returns a boolean if a field has been set.
func (o *ModelBotInstallGrant) HasRequestedPermissions() bool {
	if o != nil && !IsNil(o.RequestedPermissions) {
		return true
	}

	return false
}

// SetRequestedPermissions gets a reference to the given int32 and assigns it to the RequestedPermissions field.
func (o *ModelBotInstallGrant) SetRequestedPermissions(v int32) {
	o.RequestedPermissions = &v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise.
func (o *ModelBotInstallGrant) GetRevokedAt() string {
	if o == nil || IsNil(o.RevokedAt) {
		var ret string
		return ret
	}
	return *o.RevokedAt
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotInstallGrant) GetRevokedAtOk() (*string, bool) {
	if o == nil || IsNil(o.RevokedAt) {
		return nil, false
	}
	return o.RevokedAt, true
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *ModelBotInstallGrant) HasRevokedAt() bool {
	if o != nil && !IsNil(o.RevokedAt) {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given string and assigns it to the RevokedAt field.
func (o *ModelBotInstallGrant) SetRevokedAt(v string) {
	o.RevokedAt = &v
}

// GetTokenPrefix returns the TokenPrefix field value if set, zero value otherwise.
func (o *ModelBotInstallGrant) GetTokenPrefix() string {
	if o == nil || IsNil(o.TokenPrefix) {
		var ret string
		return ret
	}
	return *o.TokenPrefix
}

// GetTokenPrefixOk returns a tuple with the TokenPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotInstallGrant) GetTokenPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.TokenPrefix) {
		return nil, false
	}
	return o.TokenPrefix, true
}

// HasTokenPrefix returns a boolean if a field has been set.
func (o *ModelBotInstallGrant) HasTokenPrefix() bool {
	if o != nil && !IsNil(o.TokenPrefix) {
		return true
	}

	return false
}

// SetTokenPrefix gets a reference to the given string and assigns it to the TokenPrefix field.
func (o *ModelBotInstallGrant) SetTokenPrefix(v string) {
	o.TokenPrefix = &v
}

// GetUses returns the Uses field value if set, zero value otherwise.
func (o *ModelBotInstallGrant) GetUses() int32 {
	if o == nil || IsNil(o.Uses) {
		var ret int32
		return ret
	}
	return *o.Uses
}

// GetUsesOk returns a tuple with the Uses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotInstallGrant) GetUsesOk() (*int32, bool) {
	if o == nil || IsNil(o.Uses) {
		return nil, false
	}
	return o.Uses, true
}

// HasUses returns a boolean if a field has been set.
func (o *ModelBotInstallGrant) HasUses() bool {
	if o != nil && !IsNil(o.Uses) {
		return true
	}

	return false
}

// SetUses gets a reference to the given int32 and assigns it to the Uses field.
func (o *ModelBotInstallGrant) SetUses(v int32) {
	o.Uses = &v
}

func (o ModelBotInstallGrant) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelBotInstallGrant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BotUserId) {
		toSerialize["bot_user_id"] = o.BotUserId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.MaxUses) {
		toSerialize["max_uses"] = o.MaxUses
	}
	if !IsNil(o.OwnerUserId) {
		toSerialize["owner_user_id"] = o.OwnerUserId
	}
	if !IsNil(o.RequestedPermissions) {
		toSerialize["requested_permissions"] = o.RequestedPermissions
	}
	if !IsNil(o.RevokedAt) {
		toSerialize["revoked_at"] = o.RevokedAt
	}
	if !IsNil(o.TokenPrefix) {
		toSerialize["token_prefix"] = o.TokenPrefix
	}
	if !IsNil(o.Uses) {
		toSerialize["uses"] = o.Uses
	}
	return toSerialize, nil
}

type NullableModelBotInstallGrant struct {
	value *ModelBotInstallGrant
	isSet bool
}

func (v NullableModelBotInstallGrant) Get() *ModelBotInstallGrant {
	return v.value
}

func (v *NullableModelBotInstallGrant) Set(val *ModelBotInstallGrant) {
	v.value = val
	v.isSet = true
}

func (v NullableModelBotInstallGrant) IsSet() bool {
	return v.isSet
}

func (v *NullableModelBotInstallGrant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelBotInstallGrant(val *ModelBotInstallGrant) *NullableModelBotInstallGrant {
	return &NullableModelBotInstallGrant{value: val, isSet: true}
}

func (v NullableModelBotInstallGrant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelBotInstallGrant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
