/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the GuildPatchGuildRoleOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuildPatchGuildRoleOrderRequest{}

// GuildPatchGuildRoleOrderRequest struct for GuildPatchGuildRoleOrderRequest
type GuildPatchGuildRoleOrderRequest struct {
	// List of roles to change order.
	Roles []GuildRoleOrder `json:"roles,omitempty"`
}

// NewGuildPatchGuildRoleOrderRequest instantiates a new GuildPatchGuildRoleOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuildPatchGuildRoleOrderRequest() *GuildPatchGuildRoleOrderRequest {
	this := GuildPatchGuildRoleOrderRequest{}
	return &this
}

// NewGuildPatchGuildRoleOrderRequestWithDefaults instantiates a new GuildPatchGuildRoleOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuildPatchGuildRoleOrderRequestWithDefaults() *GuildPatchGuildRoleOrderRequest {
	this := GuildPatchGuildRoleOrderRequest{}
	return &this
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *GuildPatchGuildRoleOrderRequest) GetRoles() []GuildRoleOrder {
	if o == nil || IsNil(o.Roles) {
		var ret []GuildRoleOrder
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildPatchGuildRoleOrderRequest) GetRolesOk() ([]GuildRoleOrder, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *GuildPatchGuildRoleOrderRequest) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []GuildRoleOrder and assigns it to the Roles field.
func (o *GuildPatchGuildRoleOrderRequest) SetRoles(v []GuildRoleOrder) {
	o.Roles = v
}

func (o GuildPatchGuildRoleOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuildPatchGuildRoleOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	return toSerialize, nil
}

type NullableGuildPatchGuildRoleOrderRequest struct {
	value *GuildPatchGuildRoleOrderRequest
	isSet bool
}

func (v NullableGuildPatchGuildRoleOrderRequest) Get() *GuildPatchGuildRoleOrderRequest {
	return v.value
}

func (v *NullableGuildPatchGuildRoleOrderRequest) Set(val *GuildPatchGuildRoleOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGuildPatchGuildRoleOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGuildPatchGuildRoleOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuildPatchGuildRoleOrderRequest(val *GuildPatchGuildRoleOrderRequest) *NullableGuildPatchGuildRoleOrderRequest {
	return &NullableGuildPatchGuildRoleOrderRequest{value: val, isSet: true}
}

func (v NullableGuildPatchGuildRoleOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuildPatchGuildRoleOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
