/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the ModelBotToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelBotToken{}

// ModelBotToken struct for ModelBotToken
type ModelBotToken struct {
	BotUserId   *int32  `json:"bot_user_id,omitempty"`
	CreatedAt   *string `json:"created_at,omitempty"`
	Id          *int32  `json:"id,omitempty"`
	LastUsedAt  *string `json:"last_used_at,omitempty"`
	Name        *string `json:"name,omitempty"`
	RevokedAt   *string `json:"revoked_at,omitempty"`
	TokenPrefix *string `json:"token_prefix,omitempty"`
}

// NewModelBotToken instantiates a new ModelBotToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelBotToken() *ModelBotToken {
	this := ModelBotToken{}
	return &this
}

// NewModelBotTokenWithDefaults instantiates a new ModelBotToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelBotTokenWithDefaults() *ModelBotToken {
	this := ModelBotToken{}
	return &this
}

// GetBotUserId returns the BotUserId field value if set, zero value otherwise.
func (o *ModelBotToken) GetBotUserId() int32 {
	if o == nil || IsNil(o.BotUserId) {
		var ret int32
		return ret
	}
	return *o.BotUserId
}

// GetBotUserIdOk returns a tuple with the BotUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotToken) GetBotUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.BotUserId) {
		return nil, false
	}
	return o.BotUserId, true
}

// HasBotUserId returns a boolean if a field has been set.
func (o *ModelBotToken) HasBotUserId() bool {
	if o != nil && !IsNil(o.BotUserId) {
		return true
	}

	return false
}

// SetBotUserId gets a reference to the given int32 and assigns it to the BotUserId field.
func (o *ModelBotToken) SetBotUserId(v int32) {
	o.BotUserId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ModelBotToken) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotToken) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ModelBotToken) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ModelBotToken) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelBotToken) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotToken) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelBotToken) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ModelBotToken) SetId(v int32) {
	o.Id = &v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise.
func (o *ModelBotToken) GetLastUsedAt() string {
	if o == nil || IsNil(o.LastUsedAt) {
		var ret string
		return ret
	}
	return *o.LastUsedAt
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotToken) GetLastUsedAtOk() (*string, bool) {
	if o == nil || IsNil(o.LastUsedAt) {
		return nil, false
	}
	return o.LastUsedAt, true
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *ModelBotToken) HasLastUsedAt() bool {
	if o != nil && !IsNil(o.LastUsedAt) {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given string and assigns it to the LastUsedAt field.
func (o *ModelBotToken) SetLastUsedAt(v string) {
	o.LastUsedAt = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelBotToken) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotToken) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelBotToken) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelBotToken) SetName(v string) {
	o.Name = &v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise.
func (o *ModelBotToken) GetRevokedAt() string {
	if o == nil || IsNil(o.RevokedAt) {
		var ret string
		return ret
	}
	return *o.RevokedAt
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotToken) GetRevokedAtOk() (*string, bool) {
	if o == nil || IsNil(o.RevokedAt) {
		return nil, false
	}
	return o.RevokedAt, true
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *ModelBotToken) HasRevokedAt() bool {
	if o != nil && !IsNil(o.RevokedAt) {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given string and assigns it to the RevokedAt field.
func (o *ModelBotToken) SetRevokedAt(v string) {
	o.RevokedAt = &v
}

// GetTokenPrefix returns the TokenPrefix field value if set, zero value otherwise.
func (o *ModelBotToken) GetTokenPrefix() string {
	if o == nil || IsNil(o.TokenPrefix) {
		var ret string
		return ret
	}
	return *o.TokenPrefix
}

// GetTokenPrefixOk returns a tuple with the TokenPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelBotToken) GetTokenPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.TokenPrefix) {
		return nil, false
	}
	return o.TokenPrefix, true
}

// HasTokenPrefix returns a boolean if a field has been set.
func (o *ModelBotToken) HasTokenPrefix() bool {
	if o != nil && !IsNil(o.TokenPrefix) {
		return true
	}

	return false
}

// SetTokenPrefix gets a reference to the given string and assigns it to the TokenPrefix field.
func (o *ModelBotToken) SetTokenPrefix(v string) {
	o.TokenPrefix = &v
}

func (o ModelBotToken) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelBotToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BotUserId) {
		toSerialize["bot_user_id"] = o.BotUserId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LastUsedAt) {
		toSerialize["last_used_at"] = o.LastUsedAt
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RevokedAt) {
		toSerialize["revoked_at"] = o.RevokedAt
	}
	if !IsNil(o.TokenPrefix) {
		toSerialize["token_prefix"] = o.TokenPrefix
	}
	return toSerialize, nil
}

type NullableModelBotToken struct {
	value *ModelBotToken
	isSet bool
}

func (v NullableModelBotToken) Get() *ModelBotToken {
	return v.value
}

func (v *NullableModelBotToken) Set(val *ModelBotToken) {
	v.value = val
	v.isSet = true
}

func (v NullableModelBotToken) IsSet() bool {
	return v.isSet
}

func (v *NullableModelBotToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelBotToken(val *ModelBotToken) *NullableModelBotToken {
	return &NullableModelBotToken{value: val, isSet: true}
}

func (v NullableModelBotToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelBotToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
