/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the GuildMoveMemberResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuildMoveMemberResponse{}

// GuildMoveMemberResponse struct for GuildMoveMemberResponse
type GuildMoveMemberResponse struct {
	FromSfuToken *string `json:"from_sfu_token,omitempty"`
	FromSfuUrl   *string `json:"from_sfu_url,omitempty"`
	Ok           *bool   `json:"ok,omitempty"`
}

// NewGuildMoveMemberResponse instantiates a new GuildMoveMemberResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuildMoveMemberResponse() *GuildMoveMemberResponse {
	this := GuildMoveMemberResponse{}
	return &this
}

// NewGuildMoveMemberResponseWithDefaults instantiates a new GuildMoveMemberResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuildMoveMemberResponseWithDefaults() *GuildMoveMemberResponse {
	this := GuildMoveMemberResponse{}
	return &this
}

// GetFromSfuToken returns the FromSfuToken field value if set, zero value otherwise.
func (o *GuildMoveMemberResponse) GetFromSfuToken() string {
	if o == nil || IsNil(o.FromSfuToken) {
		var ret string
		return ret
	}
	return *o.FromSfuToken
}

// GetFromSfuTokenOk returns a tuple with the FromSfuToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildMoveMemberResponse) GetFromSfuTokenOk() (*string, bool) {
	if o == nil || IsNil(o.FromSfuToken) {
		return nil, false
	}
	return o.FromSfuToken, true
}

// HasFromSfuToken returns a boolean if a field has been set.
func (o *GuildMoveMemberResponse) HasFromSfuToken() bool {
	if o != nil && !IsNil(o.FromSfuToken) {
		return true
	}

	return false
}

// SetFromSfuToken gets a reference to the given string and assigns it to the FromSfuToken field.
func (o *GuildMoveMemberResponse) SetFromSfuToken(v string) {
	o.FromSfuToken = &v
}

// GetFromSfuUrl returns the FromSfuUrl field value if set, zero value otherwise.
func (o *GuildMoveMemberResponse) GetFromSfuUrl() string {
	if o == nil || IsNil(o.FromSfuUrl) {
		var ret string
		return ret
	}
	return *o.FromSfuUrl
}

// GetFromSfuUrlOk returns a tuple with the FromSfuUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildMoveMemberResponse) GetFromSfuUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FromSfuUrl) {
		return nil, false
	}
	return o.FromSfuUrl, true
}

// HasFromSfuUrl returns a boolean if a field has been set.
func (o *GuildMoveMemberResponse) HasFromSfuUrl() bool {
	if o != nil && !IsNil(o.FromSfuUrl) {
		return true
	}

	return false
}

// SetFromSfuUrl gets a reference to the given string and assigns it to the FromSfuUrl field.
func (o *GuildMoveMemberResponse) SetFromSfuUrl(v string) {
	o.FromSfuUrl = &v
}

// GetOk returns the Ok field value if set, zero value otherwise.
func (o *GuildMoveMemberResponse) GetOk() bool {
	if o == nil || IsNil(o.Ok) {
		var ret bool
		return ret
	}
	return *o.Ok
}

// GetOkOk returns a tuple with the Ok field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildMoveMemberResponse) GetOkOk() (*bool, bool) {
	if o == nil || IsNil(o.Ok) {
		return nil, false
	}
	return o.Ok, true
}

// HasOk returns a boolean if a field has been set.
func (o *GuildMoveMemberResponse) HasOk() bool {
	if o != nil && !IsNil(o.Ok) {
		return true
	}

	return false
}

// SetOk gets a reference to the given bool and assigns it to the Ok field.
func (o *GuildMoveMemberResponse) SetOk(v bool) {
	o.Ok = &v
}

func (o GuildMoveMemberResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuildMoveMemberResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FromSfuToken) {
		toSerialize["from_sfu_token"] = o.FromSfuToken
	}
	if !IsNil(o.FromSfuUrl) {
		toSerialize["from_sfu_url"] = o.FromSfuUrl
	}
	if !IsNil(o.Ok) {
		toSerialize["ok"] = o.Ok
	}
	return toSerialize, nil
}

type NullableGuildMoveMemberResponse struct {
	value *GuildMoveMemberResponse
	isSet bool
}

func (v NullableGuildMoveMemberResponse) Get() *GuildMoveMemberResponse {
	return v.value
}

func (v *NullableGuildMoveMemberResponse) Set(val *GuildMoveMemberResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGuildMoveMemberResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGuildMoveMemberResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuildMoveMemberResponse(val *GuildMoveMemberResponse) *NullableGuildMoveMemberResponse {
	return &NullableGuildMoveMemberResponse{value: val, isSet: true}
}

func (v NullableGuildMoveMemberResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuildMoveMemberResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
