/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the MessageUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageUpdateRequest{}

// MessageUpdateRequest struct for MessageUpdateRequest
type MessageUpdateRequest struct {
	Content *string      `json:"content,omitempty"`
	Embeds  []EmbedEmbed `json:"embeds,omitempty"`
	Flags   *int32       `json:"flags,omitempty"`
}

// NewMessageUpdateRequest instantiates a new MessageUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageUpdateRequest() *MessageUpdateRequest {
	this := MessageUpdateRequest{}
	return &this
}

// NewMessageUpdateRequestWithDefaults instantiates a new MessageUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageUpdateRequestWithDefaults() *MessageUpdateRequest {
	this := MessageUpdateRequest{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *MessageUpdateRequest) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageUpdateRequest) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *MessageUpdateRequest) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *MessageUpdateRequest) SetContent(v string) {
	o.Content = &v
}

// GetEmbeds returns the Embeds field value if set, zero value otherwise.
func (o *MessageUpdateRequest) GetEmbeds() []EmbedEmbed {
	if o == nil || IsNil(o.Embeds) {
		var ret []EmbedEmbed
		return ret
	}
	return o.Embeds
}

// GetEmbedsOk returns a tuple with the Embeds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageUpdateRequest) GetEmbedsOk() ([]EmbedEmbed, bool) {
	if o == nil || IsNil(o.Embeds) {
		return nil, false
	}
	return o.Embeds, true
}

// HasEmbeds returns a boolean if a field has been set.
func (o *MessageUpdateRequest) HasEmbeds() bool {
	if o != nil && !IsNil(o.Embeds) {
		return true
	}

	return false
}

// SetEmbeds gets a reference to the given []EmbedEmbed and assigns it to the Embeds field.
func (o *MessageUpdateRequest) SetEmbeds(v []EmbedEmbed) {
	o.Embeds = v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *MessageUpdateRequest) GetFlags() int32 {
	if o == nil || IsNil(o.Flags) {
		var ret int32
		return ret
	}
	return *o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageUpdateRequest) GetFlagsOk() (*int32, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *MessageUpdateRequest) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given int32 and assigns it to the Flags field.
func (o *MessageUpdateRequest) SetFlags(v int32) {
	o.Flags = &v
}

func (o MessageUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Embeds) {
		toSerialize["embeds"] = o.Embeds
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	return toSerialize, nil
}

type NullableMessageUpdateRequest struct {
	value *MessageUpdateRequest
	isSet bool
}

func (v NullableMessageUpdateRequest) Get() *MessageUpdateRequest {
	return v.value
}

func (v *NullableMessageUpdateRequest) Set(val *MessageUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageUpdateRequest(val *MessageUpdateRequest) *NullableMessageUpdateRequest {
	return &NullableMessageUpdateRequest{value: val, isSet: true}
}

func (v NullableMessageUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
