/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the UserCreateAvatarRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCreateAvatarRequest{}

// UserCreateAvatarRequest struct for UserCreateAvatarRequest
type UserCreateAvatarRequest struct {
	ContentType *string `json:"content_type,omitempty"`
	FileSize    *int32  `json:"file_size,omitempty"`
}

// NewUserCreateAvatarRequest instantiates a new UserCreateAvatarRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCreateAvatarRequest() *UserCreateAvatarRequest {
	this := UserCreateAvatarRequest{}
	return &this
}

// NewUserCreateAvatarRequestWithDefaults instantiates a new UserCreateAvatarRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCreateAvatarRequestWithDefaults() *UserCreateAvatarRequest {
	this := UserCreateAvatarRequest{}
	return &this
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *UserCreateAvatarRequest) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateAvatarRequest) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *UserCreateAvatarRequest) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *UserCreateAvatarRequest) SetContentType(v string) {
	o.ContentType = &v
}

// GetFileSize returns the FileSize field value if set, zero value otherwise.
func (o *UserCreateAvatarRequest) GetFileSize() int32 {
	if o == nil || IsNil(o.FileSize) {
		var ret int32
		return ret
	}
	return *o.FileSize
}

// GetFileSizeOk returns a tuple with the FileSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateAvatarRequest) GetFileSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.FileSize) {
		return nil, false
	}
	return o.FileSize, true
}

// HasFileSize returns a boolean if a field has been set.
func (o *UserCreateAvatarRequest) HasFileSize() bool {
	if o != nil && !IsNil(o.FileSize) {
		return true
	}

	return false
}

// SetFileSize gets a reference to the given int32 and assigns it to the FileSize field.
func (o *UserCreateAvatarRequest) SetFileSize(v int32) {
	o.FileSize = &v
}

func (o UserCreateAvatarRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCreateAvatarRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContentType) {
		toSerialize["content_type"] = o.ContentType
	}
	if !IsNil(o.FileSize) {
		toSerialize["file_size"] = o.FileSize
	}
	return toSerialize, nil
}

type NullableUserCreateAvatarRequest struct {
	value *UserCreateAvatarRequest
	isSet bool
}

func (v NullableUserCreateAvatarRequest) Get() *UserCreateAvatarRequest {
	return v.value
}

func (v *NullableUserCreateAvatarRequest) Set(val *UserCreateAvatarRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCreateAvatarRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCreateAvatarRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCreateAvatarRequest(val *UserCreateAvatarRequest) *NullableUserCreateAvatarRequest {
	return &NullableUserCreateAvatarRequest{value: val, isSet: true}
}

func (v NullableUserCreateAvatarRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCreateAvatarRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
