/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the GuildPatchGuildChannelOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuildPatchGuildChannelOrderRequest{}

// GuildPatchGuildChannelOrderRequest struct for GuildPatchGuildChannelOrderRequest
type GuildPatchGuildChannelOrderRequest struct {
	Channels []GuildChannelOrder `json:"channels,omitempty"`
}

// NewGuildPatchGuildChannelOrderRequest instantiates a new GuildPatchGuildChannelOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuildPatchGuildChannelOrderRequest() *GuildPatchGuildChannelOrderRequest {
	this := GuildPatchGuildChannelOrderRequest{}
	return &this
}

// NewGuildPatchGuildChannelOrderRequestWithDefaults instantiates a new GuildPatchGuildChannelOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuildPatchGuildChannelOrderRequestWithDefaults() *GuildPatchGuildChannelOrderRequest {
	this := GuildPatchGuildChannelOrderRequest{}
	return &this
}

// GetChannels returns the Channels field value if set, zero value otherwise.
func (o *GuildPatchGuildChannelOrderRequest) GetChannels() []GuildChannelOrder {
	if o == nil || IsNil(o.Channels) {
		var ret []GuildChannelOrder
		return ret
	}
	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildPatchGuildChannelOrderRequest) GetChannelsOk() ([]GuildChannelOrder, bool) {
	if o == nil || IsNil(o.Channels) {
		return nil, false
	}
	return o.Channels, true
}

// HasChannels returns a boolean if a field has been set.
func (o *GuildPatchGuildChannelOrderRequest) HasChannels() bool {
	if o != nil && !IsNil(o.Channels) {
		return true
	}

	return false
}

// SetChannels gets a reference to the given []GuildChannelOrder and assigns it to the Channels field.
func (o *GuildPatchGuildChannelOrderRequest) SetChannels(v []GuildChannelOrder) {
	o.Channels = v
}

func (o GuildPatchGuildChannelOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuildPatchGuildChannelOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Channels) {
		toSerialize["channels"] = o.Channels
	}
	return toSerialize, nil
}

type NullableGuildPatchGuildChannelOrderRequest struct {
	value *GuildPatchGuildChannelOrderRequest
	isSet bool
}

func (v NullableGuildPatchGuildChannelOrderRequest) Get() *GuildPatchGuildChannelOrderRequest {
	return v.value
}

func (v *NullableGuildPatchGuildChannelOrderRequest) Set(val *GuildPatchGuildChannelOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGuildPatchGuildChannelOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGuildPatchGuildChannelOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuildPatchGuildChannelOrderRequest(val *GuildPatchGuildChannelOrderRequest) *NullableGuildPatchGuildChannelOrderRequest {
	return &NullableGuildPatchGuildChannelOrderRequest{value: val, isSet: true}
}

func (v NullableGuildPatchGuildChannelOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuildPatchGuildChannelOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
