/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the GuildJoinVoiceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuildJoinVoiceResponse{}

// GuildJoinVoiceResponse struct for GuildJoinVoiceResponse
type GuildJoinVoiceResponse struct {
	SfuToken *string `json:"sfu_token,omitempty"`
	SfuUrl   *string `json:"sfu_url,omitempty"`
}

// NewGuildJoinVoiceResponse instantiates a new GuildJoinVoiceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuildJoinVoiceResponse() *GuildJoinVoiceResponse {
	this := GuildJoinVoiceResponse{}
	return &this
}

// NewGuildJoinVoiceResponseWithDefaults instantiates a new GuildJoinVoiceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuildJoinVoiceResponseWithDefaults() *GuildJoinVoiceResponse {
	this := GuildJoinVoiceResponse{}
	return &this
}

// GetSfuToken returns the SfuToken field value if set, zero value otherwise.
func (o *GuildJoinVoiceResponse) GetSfuToken() string {
	if o == nil || IsNil(o.SfuToken) {
		var ret string
		return ret
	}
	return *o.SfuToken
}

// GetSfuTokenOk returns a tuple with the SfuToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildJoinVoiceResponse) GetSfuTokenOk() (*string, bool) {
	if o == nil || IsNil(o.SfuToken) {
		return nil, false
	}
	return o.SfuToken, true
}

// HasSfuToken returns a boolean if a field has been set.
func (o *GuildJoinVoiceResponse) HasSfuToken() bool {
	if o != nil && !IsNil(o.SfuToken) {
		return true
	}

	return false
}

// SetSfuToken gets a reference to the given string and assigns it to the SfuToken field.
func (o *GuildJoinVoiceResponse) SetSfuToken(v string) {
	o.SfuToken = &v
}

// GetSfuUrl returns the SfuUrl field value if set, zero value otherwise.
func (o *GuildJoinVoiceResponse) GetSfuUrl() string {
	if o == nil || IsNil(o.SfuUrl) {
		var ret string
		return ret
	}
	return *o.SfuUrl
}

// GetSfuUrlOk returns a tuple with the SfuUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildJoinVoiceResponse) GetSfuUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SfuUrl) {
		return nil, false
	}
	return o.SfuUrl, true
}

// HasSfuUrl returns a boolean if a field has been set.
func (o *GuildJoinVoiceResponse) HasSfuUrl() bool {
	if o != nil && !IsNil(o.SfuUrl) {
		return true
	}

	return false
}

// SetSfuUrl gets a reference to the given string and assigns it to the SfuUrl field.
func (o *GuildJoinVoiceResponse) SetSfuUrl(v string) {
	o.SfuUrl = &v
}

func (o GuildJoinVoiceResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuildJoinVoiceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SfuToken) {
		toSerialize["sfu_token"] = o.SfuToken
	}
	if !IsNil(o.SfuUrl) {
		toSerialize["sfu_url"] = o.SfuUrl
	}
	return toSerialize, nil
}

type NullableGuildJoinVoiceResponse struct {
	value *GuildJoinVoiceResponse
	isSet bool
}

func (v NullableGuildJoinVoiceResponse) Get() *GuildJoinVoiceResponse {
	return v.value
}

func (v *NullableGuildJoinVoiceResponse) Set(val *GuildJoinVoiceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGuildJoinVoiceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGuildJoinVoiceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuildJoinVoiceResponse(val *GuildJoinVoiceResponse) *NullableGuildJoinVoiceResponse {
	return &NullableGuildJoinVoiceResponse{value: val, isSet: true}
}

func (v NullableGuildJoinVoiceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuildJoinVoiceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
