/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the ModelUserSettingsGuildFolders type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelUserSettingsGuildFolders{}

// ModelUserSettingsGuildFolders struct for ModelUserSettingsGuildFolders
type ModelUserSettingsGuildFolders struct {
	Color    *int32  `json:"color,omitempty"`
	Guilds   []int32 `json:"guilds,omitempty"`
	Name     *string `json:"name,omitempty"`
	Position *int32  `json:"position,omitempty"`
}

// NewModelUserSettingsGuildFolders instantiates a new ModelUserSettingsGuildFolders object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelUserSettingsGuildFolders() *ModelUserSettingsGuildFolders {
	this := ModelUserSettingsGuildFolders{}
	return &this
}

// NewModelUserSettingsGuildFoldersWithDefaults instantiates a new ModelUserSettingsGuildFolders object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelUserSettingsGuildFoldersWithDefaults() *ModelUserSettingsGuildFolders {
	this := ModelUserSettingsGuildFolders{}
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *ModelUserSettingsGuildFolders) GetColor() int32 {
	if o == nil || IsNil(o.Color) {
		var ret int32
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserSettingsGuildFolders) GetColorOk() (*int32, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *ModelUserSettingsGuildFolders) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given int32 and assigns it to the Color field.
func (o *ModelUserSettingsGuildFolders) SetColor(v int32) {
	o.Color = &v
}

// GetGuilds returns the Guilds field value if set, zero value otherwise.
func (o *ModelUserSettingsGuildFolders) GetGuilds() []int32 {
	if o == nil || IsNil(o.Guilds) {
		var ret []int32
		return ret
	}
	return o.Guilds
}

// GetGuildsOk returns a tuple with the Guilds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserSettingsGuildFolders) GetGuildsOk() ([]int32, bool) {
	if o == nil || IsNil(o.Guilds) {
		return nil, false
	}
	return o.Guilds, true
}

// HasGuilds returns a boolean if a field has been set.
func (o *ModelUserSettingsGuildFolders) HasGuilds() bool {
	if o != nil && !IsNil(o.Guilds) {
		return true
	}

	return false
}

// SetGuilds gets a reference to the given []int32 and assigns it to the Guilds field.
func (o *ModelUserSettingsGuildFolders) SetGuilds(v []int32) {
	o.Guilds = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelUserSettingsGuildFolders) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserSettingsGuildFolders) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelUserSettingsGuildFolders) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelUserSettingsGuildFolders) SetName(v string) {
	o.Name = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *ModelUserSettingsGuildFolders) GetPosition() int32 {
	if o == nil || IsNil(o.Position) {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserSettingsGuildFolders) GetPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *ModelUserSettingsGuildFolders) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *ModelUserSettingsGuildFolders) SetPosition(v int32) {
	o.Position = &v
}

func (o ModelUserSettingsGuildFolders) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelUserSettingsGuildFolders) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Guilds) {
		toSerialize["guilds"] = o.Guilds
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	return toSerialize, nil
}

type NullableModelUserSettingsGuildFolders struct {
	value *ModelUserSettingsGuildFolders
	isSet bool
}

func (v NullableModelUserSettingsGuildFolders) Get() *ModelUserSettingsGuildFolders {
	return v.value
}

func (v *NullableModelUserSettingsGuildFolders) Set(val *ModelUserSettingsGuildFolders) {
	v.value = val
	v.isSet = true
}

func (v NullableModelUserSettingsGuildFolders) IsSet() bool {
	return v.isSet
}

func (v *NullableModelUserSettingsGuildFolders) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelUserSettingsGuildFolders(val *ModelUserSettingsGuildFolders) *NullableModelUserSettingsGuildFolders {
	return &NullableModelUserSettingsGuildFolders{value: val, isSet: true}
}

func (v NullableModelUserSettingsGuildFolders) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelUserSettingsGuildFolders) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
