/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
	"fmt"
)

// ModelChannelType the model 'ModelChannelType'
type ModelChannelType int32

// List of model.ChannelType
const (
	ChannelTypeGuild         ModelChannelType = 0
	ChannelTypeGuildVoice    ModelChannelType = 1
	ChannelTypeGuildCategory ModelChannelType = 2
	ChannelTypeDM            ModelChannelType = 3
	ChannelTypeGroupDM       ModelChannelType = 4
	ChannelTypeThread        ModelChannelType = 5
)

// All allowed values of ModelChannelType enum
var AllowedModelChannelTypeEnumValues = []ModelChannelType{
	0,
	1,
	2,
	3,
	4,
	5,
}

func (v *ModelChannelType) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ModelChannelType(value)
	for _, existing := range AllowedModelChannelTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ModelChannelType", value)
}

// NewModelChannelTypeFromValue returns a pointer to a valid ModelChannelType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewModelChannelTypeFromValue(v int32) (*ModelChannelType, error) {
	ev := ModelChannelType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ModelChannelType: valid values are %v", v, AllowedModelChannelTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ModelChannelType) IsValid() bool {
	for _, existing := range AllowedModelChannelTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to model.ChannelType value
func (v ModelChannelType) Ptr() *ModelChannelType {
	return &v
}

type NullableModelChannelType struct {
	value *ModelChannelType
	isSet bool
}

func (v NullableModelChannelType) Get() *ModelChannelType {
	return v.value
}

func (v *NullableModelChannelType) Set(val *ModelChannelType) {
	v.value = val
	v.isSet = true
}

func (v NullableModelChannelType) IsSet() bool {
	return v.isSet
}

func (v *NullableModelChannelType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelChannelType(val *ModelChannelType) *NullableModelChannelType {
	return &NullableModelChannelType{value: val, isSet: true}
}

func (v NullableModelChannelType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelChannelType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
