/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the MessageSendRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageSendRequest{}

// MessageSendRequest struct for MessageSendRequest
type MessageSendRequest struct {
	Attachments []int32      `json:"attachments,omitempty"`
	Content     *string      `json:"content,omitempty"`
	Embeds      []EmbedEmbed `json:"embeds,omitempty"`
	Reference   *int32       `json:"reference,omitempty"`
}

// NewMessageSendRequest instantiates a new MessageSendRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageSendRequest() *MessageSendRequest {
	this := MessageSendRequest{}
	return &this
}

// NewMessageSendRequestWithDefaults instantiates a new MessageSendRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageSendRequestWithDefaults() *MessageSendRequest {
	this := MessageSendRequest{}
	return &this
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *MessageSendRequest) GetAttachments() []int32 {
	if o == nil || IsNil(o.Attachments) {
		var ret []int32
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSendRequest) GetAttachmentsOk() ([]int32, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *MessageSendRequest) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []int32 and assigns it to the Attachments field.
func (o *MessageSendRequest) SetAttachments(v []int32) {
	o.Attachments = v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *MessageSendRequest) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSendRequest) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *MessageSendRequest) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *MessageSendRequest) SetContent(v string) {
	o.Content = &v
}

// GetEmbeds returns the Embeds field value if set, zero value otherwise.
func (o *MessageSendRequest) GetEmbeds() []EmbedEmbed {
	if o == nil || IsNil(o.Embeds) {
		var ret []EmbedEmbed
		return ret
	}
	return o.Embeds
}

// GetEmbedsOk returns a tuple with the Embeds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSendRequest) GetEmbedsOk() ([]EmbedEmbed, bool) {
	if o == nil || IsNil(o.Embeds) {
		return nil, false
	}
	return o.Embeds, true
}

// HasEmbeds returns a boolean if a field has been set.
func (o *MessageSendRequest) HasEmbeds() bool {
	if o != nil && !IsNil(o.Embeds) {
		return true
	}

	return false
}

// SetEmbeds gets a reference to the given []EmbedEmbed and assigns it to the Embeds field.
func (o *MessageSendRequest) SetEmbeds(v []EmbedEmbed) {
	o.Embeds = v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *MessageSendRequest) GetReference() int32 {
	if o == nil || IsNil(o.Reference) {
		var ret int32
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSendRequest) GetReferenceOk() (*int32, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *MessageSendRequest) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given int32 and assigns it to the Reference field.
func (o *MessageSendRequest) SetReference(v int32) {
	o.Reference = &v
}

func (o MessageSendRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageSendRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Embeds) {
		toSerialize["embeds"] = o.Embeds
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	return toSerialize, nil
}

type NullableMessageSendRequest struct {
	value *MessageSendRequest
	isSet bool
}

func (v NullableMessageSendRequest) Get() *MessageSendRequest {
	return v.value
}

func (v *NullableMessageSendRequest) Set(val *MessageSendRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageSendRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageSendRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageSendRequest(val *MessageSendRequest) *NullableMessageSendRequest {
	return &NullableMessageSendRequest{value: val, isSet: true}
}

func (v NullableMessageSendRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageSendRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
