/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the DtoMessageReaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoMessageReaction{}

// DtoMessageReaction struct for DtoMessageReaction
type DtoMessageReaction struct {
	Count *int32                   `json:"count,omitempty"`
	Emoji *DtoMessageReactionEmoji `json:"emoji,omitempty"`
	Me    *bool                    `json:"me,omitempty"`
}

// NewDtoMessageReaction instantiates a new DtoMessageReaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoMessageReaction() *DtoMessageReaction {
	this := DtoMessageReaction{}
	return &this
}

// NewDtoMessageReactionWithDefaults instantiates a new DtoMessageReaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoMessageReactionWithDefaults() *DtoMessageReaction {
	this := DtoMessageReaction{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *DtoMessageReaction) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoMessageReaction) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *DtoMessageReaction) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *DtoMessageReaction) SetCount(v int32) {
	o.Count = &v
}

// GetEmoji returns the Emoji field value if set, zero value otherwise.
func (o *DtoMessageReaction) GetEmoji() DtoMessageReactionEmoji {
	if o == nil || IsNil(o.Emoji) {
		var ret DtoMessageReactionEmoji
		return ret
	}
	return *o.Emoji
}

// GetEmojiOk returns a tuple with the Emoji field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoMessageReaction) GetEmojiOk() (*DtoMessageReactionEmoji, bool) {
	if o == nil || IsNil(o.Emoji) {
		return nil, false
	}
	return o.Emoji, true
}

// HasEmoji returns a boolean if a field has been set.
func (o *DtoMessageReaction) HasEmoji() bool {
	if o != nil && !IsNil(o.Emoji) {
		return true
	}

	return false
}

// SetEmoji gets a reference to the given DtoMessageReactionEmoji and assigns it to the Emoji field.
func (o *DtoMessageReaction) SetEmoji(v DtoMessageReactionEmoji) {
	o.Emoji = &v
}

// GetMe returns the Me field value if set, zero value otherwise.
func (o *DtoMessageReaction) GetMe() bool {
	if o == nil || IsNil(o.Me) {
		var ret bool
		return ret
	}
	return *o.Me
}

// GetMeOk returns a tuple with the Me field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoMessageReaction) GetMeOk() (*bool, bool) {
	if o == nil || IsNil(o.Me) {
		return nil, false
	}
	return o.Me, true
}

// HasMe returns a boolean if a field has been set.
func (o *DtoMessageReaction) HasMe() bool {
	if o != nil && !IsNil(o.Me) {
		return true
	}

	return false
}

// SetMe gets a reference to the given bool and assigns it to the Me field.
func (o *DtoMessageReaction) SetMe(v bool) {
	o.Me = &v
}

func (o DtoMessageReaction) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoMessageReaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Emoji) {
		toSerialize["emoji"] = o.Emoji
	}
	if !IsNil(o.Me) {
		toSerialize["me"] = o.Me
	}
	return toSerialize, nil
}

type NullableDtoMessageReaction struct {
	value *DtoMessageReaction
	isSet bool
}

func (v NullableDtoMessageReaction) Get() *DtoMessageReaction {
	return v.value
}

func (v *NullableDtoMessageReaction) Set(val *DtoMessageReaction) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoMessageReaction) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoMessageReaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoMessageReaction(val *DtoMessageReaction) *NullableDtoMessageReaction {
	return &NullableDtoMessageReaction{value: val, isSet: true}
}

func (v NullableDtoMessageReaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoMessageReaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
