/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the GuildSetGuildSystemMessagesChannelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuildSetGuildSystemMessagesChannelRequest{}

// GuildSetGuildSystemMessagesChannelRequest struct for GuildSetGuildSystemMessagesChannelRequest
type GuildSetGuildSystemMessagesChannelRequest struct {
	// Channel ID
	ChannelId *int32 `json:"channel_id,omitempty"`
}

// NewGuildSetGuildSystemMessagesChannelRequest instantiates a new GuildSetGuildSystemMessagesChannelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuildSetGuildSystemMessagesChannelRequest() *GuildSetGuildSystemMessagesChannelRequest {
	this := GuildSetGuildSystemMessagesChannelRequest{}
	return &this
}

// NewGuildSetGuildSystemMessagesChannelRequestWithDefaults instantiates a new GuildSetGuildSystemMessagesChannelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuildSetGuildSystemMessagesChannelRequestWithDefaults() *GuildSetGuildSystemMessagesChannelRequest {
	this := GuildSetGuildSystemMessagesChannelRequest{}
	return &this
}

// GetChannelId returns the ChannelId field value if set, zero value otherwise.
func (o *GuildSetGuildSystemMessagesChannelRequest) GetChannelId() int32 {
	if o == nil || IsNil(o.ChannelId) {
		var ret int32
		return ret
	}
	return *o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildSetGuildSystemMessagesChannelRequest) GetChannelIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ChannelId) {
		return nil, false
	}
	return o.ChannelId, true
}

// HasChannelId returns a boolean if a field has been set.
func (o *GuildSetGuildSystemMessagesChannelRequest) HasChannelId() bool {
	if o != nil && !IsNil(o.ChannelId) {
		return true
	}

	return false
}

// SetChannelId gets a reference to the given int32 and assigns it to the ChannelId field.
func (o *GuildSetGuildSystemMessagesChannelRequest) SetChannelId(v int32) {
	o.ChannelId = &v
}

func (o GuildSetGuildSystemMessagesChannelRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuildSetGuildSystemMessagesChannelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChannelId) {
		toSerialize["channel_id"] = o.ChannelId
	}
	return toSerialize, nil
}

type NullableGuildSetGuildSystemMessagesChannelRequest struct {
	value *GuildSetGuildSystemMessagesChannelRequest
	isSet bool
}

func (v NullableGuildSetGuildSystemMessagesChannelRequest) Get() *GuildSetGuildSystemMessagesChannelRequest {
	return v.value
}

func (v *NullableGuildSetGuildSystemMessagesChannelRequest) Set(val *GuildSetGuildSystemMessagesChannelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGuildSetGuildSystemMessagesChannelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGuildSetGuildSystemMessagesChannelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuildSetGuildSystemMessagesChannelRequest(val *GuildSetGuildSystemMessagesChannelRequest) *NullableGuildSetGuildSystemMessagesChannelRequest {
	return &NullableGuildSetGuildSystemMessagesChannelRequest{value: val, isSet: true}
}

func (v NullableGuildSetGuildSystemMessagesChannelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuildSetGuildSystemMessagesChannelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
