/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the ModelUserSettingsNotifications type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelUserSettingsNotifications{}

// ModelUserSettingsNotifications struct for ModelUserSettingsNotifications
type ModelUserSettingsNotifications struct {
	Muted                    *bool                   `json:"muted,omitempty"`
	MutedUntil               *string                 `json:"muted_until,omitempty"`
	Notifications            *ModelNotificationsType `json:"notifications,omitempty"`
	SuppressEveryoneMentions *bool                   `json:"suppress_everyone_mentions,omitempty"`
	SuppressHereMentions     *bool                   `json:"suppress_here_mentions,omitempty"`
	SuppressRoleMentions     *bool                   `json:"suppress_role_mentions,omitempty"`
	SuppressUserMentions     *bool                   `json:"suppress_user_mentions,omitempty"`
}

// NewModelUserSettingsNotifications instantiates a new ModelUserSettingsNotifications object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelUserSettingsNotifications() *ModelUserSettingsNotifications {
	this := ModelUserSettingsNotifications{}
	return &this
}

// NewModelUserSettingsNotificationsWithDefaults instantiates a new ModelUserSettingsNotifications object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelUserSettingsNotificationsWithDefaults() *ModelUserSettingsNotifications {
	this := ModelUserSettingsNotifications{}
	return &this
}

// GetMuted returns the Muted field value if set, zero value otherwise.
func (o *ModelUserSettingsNotifications) GetMuted() bool {
	if o == nil || IsNil(o.Muted) {
		var ret bool
		return ret
	}
	return *o.Muted
}

// GetMutedOk returns a tuple with the Muted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserSettingsNotifications) GetMutedOk() (*bool, bool) {
	if o == nil || IsNil(o.Muted) {
		return nil, false
	}
	return o.Muted, true
}

// HasMuted returns a boolean if a field has been set.
func (o *ModelUserSettingsNotifications) HasMuted() bool {
	if o != nil && !IsNil(o.Muted) {
		return true
	}

	return false
}

// SetMuted gets a reference to the given bool and assigns it to the Muted field.
func (o *ModelUserSettingsNotifications) SetMuted(v bool) {
	o.Muted = &v
}

// GetMutedUntil returns the MutedUntil field value if set, zero value otherwise.
func (o *ModelUserSettingsNotifications) GetMutedUntil() string {
	if o == nil || IsNil(o.MutedUntil) {
		var ret string
		return ret
	}
	return *o.MutedUntil
}

// GetMutedUntilOk returns a tuple with the MutedUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserSettingsNotifications) GetMutedUntilOk() (*string, bool) {
	if o == nil || IsNil(o.MutedUntil) {
		return nil, false
	}
	return o.MutedUntil, true
}

// HasMutedUntil returns a boolean if a field has been set.
func (o *ModelUserSettingsNotifications) HasMutedUntil() bool {
	if o != nil && !IsNil(o.MutedUntil) {
		return true
	}

	return false
}

// SetMutedUntil gets a reference to the given string and assigns it to the MutedUntil field.
func (o *ModelUserSettingsNotifications) SetMutedUntil(v string) {
	o.MutedUntil = &v
}

// GetNotifications returns the Notifications field value if set, zero value otherwise.
func (o *ModelUserSettingsNotifications) GetNotifications() ModelNotificationsType {
	if o == nil || IsNil(o.Notifications) {
		var ret ModelNotificationsType
		return ret
	}
	return *o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserSettingsNotifications) GetNotificationsOk() (*ModelNotificationsType, bool) {
	if o == nil || IsNil(o.Notifications) {
		return nil, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *ModelUserSettingsNotifications) HasNotifications() bool {
	if o != nil && !IsNil(o.Notifications) {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given ModelNotificationsType and assigns it to the Notifications field.
func (o *ModelUserSettingsNotifications) SetNotifications(v ModelNotificationsType) {
	o.Notifications = &v
}

// GetSuppressEveryoneMentions returns the SuppressEveryoneMentions field value if set, zero value otherwise.
func (o *ModelUserSettingsNotifications) GetSuppressEveryoneMentions() bool {
	if o == nil || IsNil(o.SuppressEveryoneMentions) {
		var ret bool
		return ret
	}
	return *o.SuppressEveryoneMentions
}

// GetSuppressEveryoneMentionsOk returns a tuple with the SuppressEveryoneMentions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserSettingsNotifications) GetSuppressEveryoneMentionsOk() (*bool, bool) {
	if o == nil || IsNil(o.SuppressEveryoneMentions) {
		return nil, false
	}
	return o.SuppressEveryoneMentions, true
}

// HasSuppressEveryoneMentions returns a boolean if a field has been set.
func (o *ModelUserSettingsNotifications) HasSuppressEveryoneMentions() bool {
	if o != nil && !IsNil(o.SuppressEveryoneMentions) {
		return true
	}

	return false
}

// SetSuppressEveryoneMentions gets a reference to the given bool and assigns it to the SuppressEveryoneMentions field.
func (o *ModelUserSettingsNotifications) SetSuppressEveryoneMentions(v bool) {
	o.SuppressEveryoneMentions = &v
}

// GetSuppressHereMentions returns the SuppressHereMentions field value if set, zero value otherwise.
func (o *ModelUserSettingsNotifications) GetSuppressHereMentions() bool {
	if o == nil || IsNil(o.SuppressHereMentions) {
		var ret bool
		return ret
	}
	return *o.SuppressHereMentions
}

// GetSuppressHereMentionsOk returns a tuple with the SuppressHereMentions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserSettingsNotifications) GetSuppressHereMentionsOk() (*bool, bool) {
	if o == nil || IsNil(o.SuppressHereMentions) {
		return nil, false
	}
	return o.SuppressHereMentions, true
}

// HasSuppressHereMentions returns a boolean if a field has been set.
func (o *ModelUserSettingsNotifications) HasSuppressHereMentions() bool {
	if o != nil && !IsNil(o.SuppressHereMentions) {
		return true
	}

	return false
}

// SetSuppressHereMentions gets a reference to the given bool and assigns it to the SuppressHereMentions field.
func (o *ModelUserSettingsNotifications) SetSuppressHereMentions(v bool) {
	o.SuppressHereMentions = &v
}

// GetSuppressRoleMentions returns the SuppressRoleMentions field value if set, zero value otherwise.
func (o *ModelUserSettingsNotifications) GetSuppressRoleMentions() bool {
	if o == nil || IsNil(o.SuppressRoleMentions) {
		var ret bool
		return ret
	}
	return *o.SuppressRoleMentions
}

// GetSuppressRoleMentionsOk returns a tuple with the SuppressRoleMentions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserSettingsNotifications) GetSuppressRoleMentionsOk() (*bool, bool) {
	if o == nil || IsNil(o.SuppressRoleMentions) {
		return nil, false
	}
	return o.SuppressRoleMentions, true
}

// HasSuppressRoleMentions returns a boolean if a field has been set.
func (o *ModelUserSettingsNotifications) HasSuppressRoleMentions() bool {
	if o != nil && !IsNil(o.SuppressRoleMentions) {
		return true
	}

	return false
}

// SetSuppressRoleMentions gets a reference to the given bool and assigns it to the SuppressRoleMentions field.
func (o *ModelUserSettingsNotifications) SetSuppressRoleMentions(v bool) {
	o.SuppressRoleMentions = &v
}

// GetSuppressUserMentions returns the SuppressUserMentions field value if set, zero value otherwise.
func (o *ModelUserSettingsNotifications) GetSuppressUserMentions() bool {
	if o == nil || IsNil(o.SuppressUserMentions) {
		var ret bool
		return ret
	}
	return *o.SuppressUserMentions
}

// GetSuppressUserMentionsOk returns a tuple with the SuppressUserMentions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserSettingsNotifications) GetSuppressUserMentionsOk() (*bool, bool) {
	if o == nil || IsNil(o.SuppressUserMentions) {
		return nil, false
	}
	return o.SuppressUserMentions, true
}

// HasSuppressUserMentions returns a boolean if a field has been set.
func (o *ModelUserSettingsNotifications) HasSuppressUserMentions() bool {
	if o != nil && !IsNil(o.SuppressUserMentions) {
		return true
	}

	return false
}

// SetSuppressUserMentions gets a reference to the given bool and assigns it to the SuppressUserMentions field.
func (o *ModelUserSettingsNotifications) SetSuppressUserMentions(v bool) {
	o.SuppressUserMentions = &v
}

func (o ModelUserSettingsNotifications) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelUserSettingsNotifications) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Muted) {
		toSerialize["muted"] = o.Muted
	}
	if !IsNil(o.MutedUntil) {
		toSerialize["muted_until"] = o.MutedUntil
	}
	if !IsNil(o.Notifications) {
		toSerialize["notifications"] = o.Notifications
	}
	if !IsNil(o.SuppressEveryoneMentions) {
		toSerialize["suppress_everyone_mentions"] = o.SuppressEveryoneMentions
	}
	if !IsNil(o.SuppressHereMentions) {
		toSerialize["suppress_here_mentions"] = o.SuppressHereMentions
	}
	if !IsNil(o.SuppressRoleMentions) {
		toSerialize["suppress_role_mentions"] = o.SuppressRoleMentions
	}
	if !IsNil(o.SuppressUserMentions) {
		toSerialize["suppress_user_mentions"] = o.SuppressUserMentions
	}
	return toSerialize, nil
}

type NullableModelUserSettingsNotifications struct {
	value *ModelUserSettingsNotifications
	isSet bool
}

func (v NullableModelUserSettingsNotifications) Get() *ModelUserSettingsNotifications {
	return v.value
}

func (v *NullableModelUserSettingsNotifications) Set(val *ModelUserSettingsNotifications) {
	v.value = val
	v.isSet = true
}

func (v NullableModelUserSettingsNotifications) IsSet() bool {
	return v.isSet
}

func (v *NullableModelUserSettingsNotifications) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelUserSettingsNotifications(val *ModelUserSettingsNotifications) *NullableModelUserSettingsNotifications {
	return &NullableModelUserSettingsNotifications{value: val, isSet: true}
}

func (v NullableModelUserSettingsNotifications) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelUserSettingsNotifications) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
