/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the DtoThreadMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoThreadMember{}

// DtoThreadMember struct for DtoThreadMember
type DtoThreadMember struct {
	Flags         *int32  `json:"flags,omitempty"`
	JoinTimestamp *string `json:"join_timestamp,omitempty"`
	UserId        *int32  `json:"user_id,omitempty"`
}

// NewDtoThreadMember instantiates a new DtoThreadMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoThreadMember() *DtoThreadMember {
	this := DtoThreadMember{}
	return &this
}

// NewDtoThreadMemberWithDefaults instantiates a new DtoThreadMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoThreadMemberWithDefaults() *DtoThreadMember {
	this := DtoThreadMember{}
	return &this
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *DtoThreadMember) GetFlags() int32 {
	if o == nil || IsNil(o.Flags) {
		var ret int32
		return ret
	}
	return *o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoThreadMember) GetFlagsOk() (*int32, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *DtoThreadMember) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given int32 and assigns it to the Flags field.
func (o *DtoThreadMember) SetFlags(v int32) {
	o.Flags = &v
}

// GetJoinTimestamp returns the JoinTimestamp field value if set, zero value otherwise.
func (o *DtoThreadMember) GetJoinTimestamp() string {
	if o == nil || IsNil(o.JoinTimestamp) {
		var ret string
		return ret
	}
	return *o.JoinTimestamp
}

// GetJoinTimestampOk returns a tuple with the JoinTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoThreadMember) GetJoinTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.JoinTimestamp) {
		return nil, false
	}
	return o.JoinTimestamp, true
}

// HasJoinTimestamp returns a boolean if a field has been set.
func (o *DtoThreadMember) HasJoinTimestamp() bool {
	if o != nil && !IsNil(o.JoinTimestamp) {
		return true
	}

	return false
}

// SetJoinTimestamp gets a reference to the given string and assigns it to the JoinTimestamp field.
func (o *DtoThreadMember) SetJoinTimestamp(v string) {
	o.JoinTimestamp = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *DtoThreadMember) GetUserId() int32 {
	if o == nil || IsNil(o.UserId) {
		var ret int32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoThreadMember) GetUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *DtoThreadMember) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int32 and assigns it to the UserId field.
func (o *DtoThreadMember) SetUserId(v int32) {
	o.UserId = &v
}

func (o DtoThreadMember) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoThreadMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	if !IsNil(o.JoinTimestamp) {
		toSerialize["join_timestamp"] = o.JoinTimestamp
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	return toSerialize, nil
}

type NullableDtoThreadMember struct {
	value *DtoThreadMember
	isSet bool
}

func (v NullableDtoThreadMember) Get() *DtoThreadMember {
	return v.value
}

func (v *NullableDtoThreadMember) Set(val *DtoThreadMember) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoThreadMember) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoThreadMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoThreadMember(val *DtoThreadMember) *NullableDtoThreadMember {
	return &NullableDtoThreadMember{value: val, isSet: true}
}

func (v NullableDtoThreadMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoThreadMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
