/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the DtoMessageReactionUsersPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoMessageReactionUsersPage{}

// DtoMessageReactionUsersPage struct for DtoMessageReactionUsersPage
type DtoMessageReactionUsersPage struct {
	Items     []DtoUser `json:"items,omitempty"`
	NextAfter *int32    `json:"next_after,omitempty"`
}

// NewDtoMessageReactionUsersPage instantiates a new DtoMessageReactionUsersPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoMessageReactionUsersPage() *DtoMessageReactionUsersPage {
	this := DtoMessageReactionUsersPage{}
	return &this
}

// NewDtoMessageReactionUsersPageWithDefaults instantiates a new DtoMessageReactionUsersPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoMessageReactionUsersPageWithDefaults() *DtoMessageReactionUsersPage {
	this := DtoMessageReactionUsersPage{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *DtoMessageReactionUsersPage) GetItems() []DtoUser {
	if o == nil || IsNil(o.Items) {
		var ret []DtoUser
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoMessageReactionUsersPage) GetItemsOk() ([]DtoUser, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *DtoMessageReactionUsersPage) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []DtoUser and assigns it to the Items field.
func (o *DtoMessageReactionUsersPage) SetItems(v []DtoUser) {
	o.Items = v
}

// GetNextAfter returns the NextAfter field value if set, zero value otherwise.
func (o *DtoMessageReactionUsersPage) GetNextAfter() int32 {
	if o == nil || IsNil(o.NextAfter) {
		var ret int32
		return ret
	}
	return *o.NextAfter
}

// GetNextAfterOk returns a tuple with the NextAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoMessageReactionUsersPage) GetNextAfterOk() (*int32, bool) {
	if o == nil || IsNil(o.NextAfter) {
		return nil, false
	}
	return o.NextAfter, true
}

// HasNextAfter returns a boolean if a field has been set.
func (o *DtoMessageReactionUsersPage) HasNextAfter() bool {
	if o != nil && !IsNil(o.NextAfter) {
		return true
	}

	return false
}

// SetNextAfter gets a reference to the given int32 and assigns it to the NextAfter field.
func (o *DtoMessageReactionUsersPage) SetNextAfter(v int32) {
	o.NextAfter = &v
}

func (o DtoMessageReactionUsersPage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoMessageReactionUsersPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.NextAfter) {
		toSerialize["next_after"] = o.NextAfter
	}
	return toSerialize, nil
}

type NullableDtoMessageReactionUsersPage struct {
	value *DtoMessageReactionUsersPage
	isSet bool
}

func (v NullableDtoMessageReactionUsersPage) Get() *DtoMessageReactionUsersPage {
	return v.value
}

func (v *NullableDtoMessageReactionUsersPage) Set(val *DtoMessageReactionUsersPage) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoMessageReactionUsersPage) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoMessageReactionUsersPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoMessageReactionUsersPage(val *DtoMessageReactionUsersPage) *NullableDtoMessageReactionUsersPage {
	return &NullableDtoMessageReactionUsersPage{value: val, isSet: true}
}

func (v NullableDtoMessageReactionUsersPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoMessageReactionUsersPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
