/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the GuildCreateGuildRoleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuildCreateGuildRoleRequest{}

// GuildCreateGuildRoleRequest struct for GuildCreateGuildRoleRequest
type GuildCreateGuildRoleRequest struct {
	// RGB int value
	Color *int32 `json:"color,omitempty"`
	// Role name
	Name *string `json:"name,omitempty"`
	// Permissions bitset
	Permissions *int32 `json:"permissions,omitempty"`
}

// NewGuildCreateGuildRoleRequest instantiates a new GuildCreateGuildRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuildCreateGuildRoleRequest() *GuildCreateGuildRoleRequest {
	this := GuildCreateGuildRoleRequest{}
	var permissions int32 = 0
	this.Permissions = &permissions
	return &this
}

// NewGuildCreateGuildRoleRequestWithDefaults instantiates a new GuildCreateGuildRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuildCreateGuildRoleRequestWithDefaults() *GuildCreateGuildRoleRequest {
	this := GuildCreateGuildRoleRequest{}
	var permissions int32 = 0
	this.Permissions = &permissions
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *GuildCreateGuildRoleRequest) GetColor() int32 {
	if o == nil || IsNil(o.Color) {
		var ret int32
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildCreateGuildRoleRequest) GetColorOk() (*int32, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *GuildCreateGuildRoleRequest) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given int32 and assigns it to the Color field.
func (o *GuildCreateGuildRoleRequest) SetColor(v int32) {
	o.Color = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GuildCreateGuildRoleRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildCreateGuildRoleRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GuildCreateGuildRoleRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GuildCreateGuildRoleRequest) SetName(v string) {
	o.Name = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *GuildCreateGuildRoleRequest) GetPermissions() int32 {
	if o == nil || IsNil(o.Permissions) {
		var ret int32
		return ret
	}
	return *o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildCreateGuildRoleRequest) GetPermissionsOk() (*int32, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *GuildCreateGuildRoleRequest) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given int32 and assigns it to the Permissions field.
func (o *GuildCreateGuildRoleRequest) SetPermissions(v int32) {
	o.Permissions = &v
}

func (o GuildCreateGuildRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuildCreateGuildRoleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return toSerialize, nil
}

type NullableGuildCreateGuildRoleRequest struct {
	value *GuildCreateGuildRoleRequest
	isSet bool
}

func (v NullableGuildCreateGuildRoleRequest) Get() *GuildCreateGuildRoleRequest {
	return v.value
}

func (v *NullableGuildCreateGuildRoleRequest) Set(val *GuildCreateGuildRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGuildCreateGuildRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGuildCreateGuildRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuildCreateGuildRoleRequest(val *GuildCreateGuildRoleRequest) *NullableGuildCreateGuildRoleRequest {
	return &NullableGuildCreateGuildRoleRequest{value: val, isSet: true}
}

func (v NullableGuildCreateGuildRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuildCreateGuildRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
