/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
	"time"
)

// checks if the EmbedEmbed type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmbedEmbed{}

// EmbedEmbed struct for EmbedEmbed
type EmbedEmbed struct {
	// Embed author metadata.
	Author *EmbedEmbedAuthor `json:"author,omitempty"`
	// Decimal RGB color value.
	Color *int32 `json:"color,omitempty"`
	// Main embed description.
	Description *string `json:"description,omitempty"`
	// Up to 25 structured fields.
	Fields []EmbedEmbedField `json:"fields,omitempty"`
	// Optional footer block.
	Footer *EmbedEmbedFooter `json:"footer,omitempty"`
	// Full-size image block.
	Image *EmbedEmbedMedia `json:"image,omitempty"`
	// Content provider metadata.
	Provider *EmbedEmbedProvider `json:"provider,omitempty"`
	// Thumbnail image block.
	Thumbnail *EmbedEmbedMedia `json:"thumbnail,omitempty"`
	// Optional ISO timestamp shown by the client.
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Embed title.
	Title *string `json:"title,omitempty"`
	// Embed type.
	Type *string `json:"type,omitempty"`
	// Canonical URL opened when the embed title is clicked.
	Url *string `json:"url,omitempty"`
	// Embedded video metadata.
	Video *EmbedEmbedMedia `json:"video,omitempty"`
}

// NewEmbedEmbed instantiates a new EmbedEmbed object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbedEmbed() *EmbedEmbed {
	this := EmbedEmbed{}
	return &this
}

// NewEmbedEmbedWithDefaults instantiates a new EmbedEmbed object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbedEmbedWithDefaults() *EmbedEmbed {
	this := EmbedEmbed{}
	return &this
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *EmbedEmbed) GetAuthor() EmbedEmbedAuthor {
	if o == nil || IsNil(o.Author) {
		var ret EmbedEmbedAuthor
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbedEmbed) GetAuthorOk() (*EmbedEmbedAuthor, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *EmbedEmbed) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given EmbedEmbedAuthor and assigns it to the Author field.
func (o *EmbedEmbed) SetAuthor(v EmbedEmbedAuthor) {
	o.Author = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *EmbedEmbed) GetColor() int32 {
	if o == nil || IsNil(o.Color) {
		var ret int32
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbedEmbed) GetColorOk() (*int32, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *EmbedEmbed) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given int32 and assigns it to the Color field.
func (o *EmbedEmbed) SetColor(v int32) {
	o.Color = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EmbedEmbed) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbedEmbed) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EmbedEmbed) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EmbedEmbed) SetDescription(v string) {
	o.Description = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *EmbedEmbed) GetFields() []EmbedEmbedField {
	if o == nil || IsNil(o.Fields) {
		var ret []EmbedEmbedField
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbedEmbed) GetFieldsOk() ([]EmbedEmbedField, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *EmbedEmbed) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []EmbedEmbedField and assigns it to the Fields field.
func (o *EmbedEmbed) SetFields(v []EmbedEmbedField) {
	o.Fields = v
}

// GetFooter returns the Footer field value if set, zero value otherwise.
func (o *EmbedEmbed) GetFooter() EmbedEmbedFooter {
	if o == nil || IsNil(o.Footer) {
		var ret EmbedEmbedFooter
		return ret
	}
	return *o.Footer
}

// GetFooterOk returns a tuple with the Footer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbedEmbed) GetFooterOk() (*EmbedEmbedFooter, bool) {
	if o == nil || IsNil(o.Footer) {
		return nil, false
	}
	return o.Footer, true
}

// HasFooter returns a boolean if a field has been set.
func (o *EmbedEmbed) HasFooter() bool {
	if o != nil && !IsNil(o.Footer) {
		return true
	}

	return false
}

// SetFooter gets a reference to the given EmbedEmbedFooter and assigns it to the Footer field.
func (o *EmbedEmbed) SetFooter(v EmbedEmbedFooter) {
	o.Footer = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *EmbedEmbed) GetImage() EmbedEmbedMedia {
	if o == nil || IsNil(o.Image) {
		var ret EmbedEmbedMedia
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbedEmbed) GetImageOk() (*EmbedEmbedMedia, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *EmbedEmbed) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given EmbedEmbedMedia and assigns it to the Image field.
func (o *EmbedEmbed) SetImage(v EmbedEmbedMedia) {
	o.Image = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *EmbedEmbed) GetProvider() EmbedEmbedProvider {
	if o == nil || IsNil(o.Provider) {
		var ret EmbedEmbedProvider
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbedEmbed) GetProviderOk() (*EmbedEmbedProvider, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *EmbedEmbed) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given EmbedEmbedProvider and assigns it to the Provider field.
func (o *EmbedEmbed) SetProvider(v EmbedEmbedProvider) {
	o.Provider = &v
}

// GetThumbnail returns the Thumbnail field value if set, zero value otherwise.
func (o *EmbedEmbed) GetThumbnail() EmbedEmbedMedia {
	if o == nil || IsNil(o.Thumbnail) {
		var ret EmbedEmbedMedia
		return ret
	}
	return *o.Thumbnail
}

// GetThumbnailOk returns a tuple with the Thumbnail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbedEmbed) GetThumbnailOk() (*EmbedEmbedMedia, bool) {
	if o == nil || IsNil(o.Thumbnail) {
		return nil, false
	}
	return o.Thumbnail, true
}

// HasThumbnail returns a boolean if a field has been set.
func (o *EmbedEmbed) HasThumbnail() bool {
	if o != nil && !IsNil(o.Thumbnail) {
		return true
	}

	return false
}

// SetThumbnail gets a reference to the given EmbedEmbedMedia and assigns it to the Thumbnail field.
func (o *EmbedEmbed) SetThumbnail(v EmbedEmbedMedia) {
	o.Thumbnail = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *EmbedEmbed) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbedEmbed) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *EmbedEmbed) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *EmbedEmbed) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *EmbedEmbed) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbedEmbed) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *EmbedEmbed) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *EmbedEmbed) SetTitle(v string) {
	o.Title = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EmbedEmbed) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbedEmbed) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EmbedEmbed) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *EmbedEmbed) SetType(v string) {
	o.Type = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *EmbedEmbed) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbedEmbed) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *EmbedEmbed) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *EmbedEmbed) SetUrl(v string) {
	o.Url = &v
}

// GetVideo returns the Video field value if set, zero value otherwise.
func (o *EmbedEmbed) GetVideo() EmbedEmbedMedia {
	if o == nil || IsNil(o.Video) {
		var ret EmbedEmbedMedia
		return ret
	}
	return *o.Video
}

// GetVideoOk returns a tuple with the Video field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbedEmbed) GetVideoOk() (*EmbedEmbedMedia, bool) {
	if o == nil || IsNil(o.Video) {
		return nil, false
	}
	return o.Video, true
}

// HasVideo returns a boolean if a field has been set.
func (o *EmbedEmbed) HasVideo() bool {
	if o != nil && !IsNil(o.Video) {
		return true
	}

	return false
}

// SetVideo gets a reference to the given EmbedEmbedMedia and assigns it to the Video field.
func (o *EmbedEmbed) SetVideo(v EmbedEmbedMedia) {
	o.Video = &v
}

func (o EmbedEmbed) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmbedEmbed) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.Footer) {
		toSerialize["footer"] = o.Footer
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Thumbnail) {
		toSerialize["thumbnail"] = o.Thumbnail
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Video) {
		toSerialize["video"] = o.Video
	}
	return toSerialize, nil
}

type NullableEmbedEmbed struct {
	value *EmbedEmbed
	isSet bool
}

func (v NullableEmbedEmbed) Get() *EmbedEmbed {
	return v.value
}

func (v *NullableEmbedEmbed) Set(val *EmbedEmbed) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbedEmbed) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbedEmbed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbedEmbed(val *EmbedEmbed) *NullableEmbedEmbed {
	return &NullableEmbedEmbed{value: val, isSet: true}
}

func (v NullableEmbedEmbed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbedEmbed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
