/*
GoChat API

This is an API for the GoChat

API version: 1.0
Contact: viktorfreedom@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goclient

import (
	"encoding/json"
)

// checks if the ModelUserSettingsUsers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelUserSettingsUsers{}

// ModelUserSettingsUsers struct for ModelUserSettingsUsers
type ModelUserSettingsUsers struct {
	Notifications *ModelUserSettingsNotifications `json:"notifications,omitempty"`
	UserId        *int32                          `json:"user_id,omitempty"`
}

// NewModelUserSettingsUsers instantiates a new ModelUserSettingsUsers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelUserSettingsUsers() *ModelUserSettingsUsers {
	this := ModelUserSettingsUsers{}
	return &this
}

// NewModelUserSettingsUsersWithDefaults instantiates a new ModelUserSettingsUsers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelUserSettingsUsersWithDefaults() *ModelUserSettingsUsers {
	this := ModelUserSettingsUsers{}
	return &this
}

// GetNotifications returns the Notifications field value if set, zero value otherwise.
func (o *ModelUserSettingsUsers) GetNotifications() ModelUserSettingsNotifications {
	if o == nil || IsNil(o.Notifications) {
		var ret ModelUserSettingsNotifications
		return ret
	}
	return *o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserSettingsUsers) GetNotificationsOk() (*ModelUserSettingsNotifications, bool) {
	if o == nil || IsNil(o.Notifications) {
		return nil, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *ModelUserSettingsUsers) HasNotifications() bool {
	if o != nil && !IsNil(o.Notifications) {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given ModelUserSettingsNotifications and assigns it to the Notifications field.
func (o *ModelUserSettingsUsers) SetNotifications(v ModelUserSettingsNotifications) {
	o.Notifications = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *ModelUserSettingsUsers) GetUserId() int32 {
	if o == nil || IsNil(o.UserId) {
		var ret int32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelUserSettingsUsers) GetUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *ModelUserSettingsUsers) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int32 and assigns it to the UserId field.
func (o *ModelUserSettingsUsers) SetUserId(v int32) {
	o.UserId = &v
}

func (o ModelUserSettingsUsers) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelUserSettingsUsers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Notifications) {
		toSerialize["notifications"] = o.Notifications
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	return toSerialize, nil
}

type NullableModelUserSettingsUsers struct {
	value *ModelUserSettingsUsers
	isSet bool
}

func (v NullableModelUserSettingsUsers) Get() *ModelUserSettingsUsers {
	return v.value
}

func (v *NullableModelUserSettingsUsers) Set(val *ModelUserSettingsUsers) {
	v.value = val
	v.isSet = true
}

func (v NullableModelUserSettingsUsers) IsSet() bool {
	return v.isSet
}

func (v *NullableModelUserSettingsUsers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelUserSettingsUsers(val *ModelUserSettingsUsers) *NullableModelUserSettingsUsers {
	return &NullableModelUserSettingsUsers{value: val, isSet: true}
}

func (v NullableModelUserSettingsUsers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelUserSettingsUsers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
