api_log: true
idempotency_storage_lifetime: 10
rate_limit_time: 1
rate_limit_requests: 20
app_name: "GoChat"
base_url: "http://example.com"
email_source: "no-reply@example.com"
email_name: "no-reply"
email_template: "./email_notify.tmpl"
password_reset_template: "./password_reset.tmpl"
email_provider: "log"
sendpulse_user_id: ""
sendpulse_secret: ""
auth_secret: "change_me_before_use_it_in_production"
swagger: false
keydb: "keydb:6379"
pg_dsn: "host=citus-master port=5432 user=postgres dbname=gochat sslmode=disable"
server_address: ":3100"