services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    restart: always

  scylla:
    image: scylladb/scylla:6.2
    volumes:
      - scylla-data:/var/lib/scylla
      - ./init/init-scylladb.sh:/init-scylladb.sh
    ports:
      - "7000:7000"
      - "9042:9042"
      - "7199:7199"
    environment:
      - SCYLLA_DEVELOPER_MODE=1
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "SELECT now() FROM system.local;"]
      interval: 10s
      retries: 5
    restart: always

  nats:
    image: nats:2.10.22-alpine3.20
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    restart: always

  keydb:
    image: eqalpha/keydb:alpine
    ports:
      - "6379:6379"
    restart: always

  api:
    image: gochat/api
    build:
      dockerfile: api.Dockerfile
    restart: always
    volumes:
      - ./api_config.yaml:/dist/config.yaml
      - ./email_notify.tmpl:/dist/email_notify.tmpl
    ports:
      - "3000:3000"
    depends_on:
      scylla:
        condition: service_healthy
      keydb:
        condition: service_started
      nats:
        condition: service_started

  ws:
    image: gochat/ws
    build:
      dockerfile: ws.Dockerfile
    restart: always
    volumes:
      - ./ws_config.yaml:/dist/config.yaml
    ports:
      - "3100:3100"
    depends_on:
      nats:
        condition: service_started

  solr:
    image: solr:8
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr
    command:
      - solr-precreate
      - gochat
    restart: always

  nginx:
    image: nginx:1.27.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always

volumes:
  scylla-data:
  solr-data: