server_address: ":3300"
auth_secret: "change_me_before_use_it_in_production"
stun_servers:
  - "stun:stun.l.google.com:19302"
region: "eu-central"
public_base_url: "https://sfu-eu.example.com"

# Webhook discovery
webhook_url: "http://webhook:3200/api/v1/webhook/sfu/heartbeat"
# Pre-generated JWT token for webhook authentication (typ=sfu, id=<service_id>)
webhook_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
# Should match service_id from the token
service_id: ""
