{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gochat.fullname" . }}-api
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "15"
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "gochat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "gochat.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          env:
            - name: S3_ACCESS_KEY_ID
              value: {{ .Values.minio.apiAccessKey | default "" | quote }}
            - name: S3_SECRET_ACCESS_KEY
              value: {{ .Values.minio.apiSecretKey | default "" | quote }}
          volumeMounts:
            - name: config
              mountPath: /dist/config.yaml
              subPath: config.yaml
            - name: email-template
              mountPath: /config/email_notify.tmpl
              subPath: email_notify.tmpl
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "gochat.fullname" . }}-api
            items:
              - key: config.yaml
                path: config.yaml
        - name: email-template
          configMap:
            name: {{ include "gochat.fullname" . }}-api
            items:
              - key: email_notify.tmpl
                path: email_notify.tmpl
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 