{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gochat.fullname" . }}-grafana-datasources
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  grafana-datasources.yaml: |-
    {{- $fullname := include "gochat.fullname" . -}}
    {{- $datasources := list -}}
    {{- if .Values.prometheus.enabled -}}
      {{- $promDatasource := .Values.grafana.datasources.prometheus -}}
      {{- $promData := dict "name" $promDatasource.name "type" $promDatasource.type "url" (printf "http://%s-%s:%d" $fullname $promDatasource.serviceName (int $promDatasource.servicePort)) "access" $promDatasource.access "isDefault" $promDatasource.isDefault "jsonData" (dict "timeInterval" "5s") -}}
      {{- $datasources = append $datasources $promData -}}
    {{- end -}}
    {{- if .Values.loki.enabled -}}
      {{- $lokiDatasource := .Values.grafana.datasources.loki -}}
      {{- $lokiData := dict "name" $lokiDatasource.name "type" $lokiDatasource.type "url" (printf "http://%s-%s:%d" $fullname $lokiDatasource.serviceName (int $lokiDatasource.servicePort)) "access" $lokiDatasource.access "isDefault" $lokiDatasource.isDefault "jsonData" (dict "maxLines" 1000) -}}
      {{- $datasources = append $datasources $lokiData -}}
    {{- end -}}
    {{- $configData := dict "apiVersion" 1 "datasources" $datasources -}}
    {{ $configData | toYaml | nindent 4 }}
{{- end }} 