{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gochat.fullname" . }}-grafana
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gochat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }} 