{{- if and .Values.ingress.enabled .Values.ingressWs.enabled -}}
{{- $fullName := include "gochat.fullname" . -}}
{{- $wsSvcPort := .Values.ws.service.port -}}
{{- $hostName := .Values.ingress.hostOverride }}
{{- if not $hostName }}
  {{- if .Values.ingress.hosts }}
    {{- $hostName = (first .Values.ingress.hosts).host }}
  {{- else }}
    {{- $hostName = printf "%s-default.%s" $fullName "local" }}
  {{- end }}
{{- end }}
{{- $ingressClassName := .Values.ingressWs.className | default .Values.ingress.className | default "" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ws
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress-ws
  annotations:
    {{- with .Values.ingressWs.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and $ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ $hostName | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- else if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- if .hosts }}
          {{- tpl (toYaml .hosts) $ | nindent 10 }}
        {{- else }}
          - {{ $hostName | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $hostName | quote }}
      http:
        paths:
          - path: /ws(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-ws
                port:
                  name: ws
{{- end }} 