{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gochat.fullname" . -}}
{{- $svcPortApi := .Values.api.service.port -}}
{{- $svcPortWs := .Values.ws.service.port -}}
{{- $svcPortMinio := .Values.minio.service.apiPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- /* Apply annotations from values.yaml */}}
    {{- toYaml . | nindent 4 }}
    {{- /* Remove hardcoded annotations below */}}
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # nginx.ingress.kubernetes.io/websocket-services: "gochat-ws"
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- /* Determine hostname: use override if set, otherwise use first host from list */}}
  {{- $hostName := .Values.ingress.hostOverride }}
  {{- /* If hostOverride is an empty string, fall back to hosts list or default */}}
  {{- if eq $hostName "" }}
    {{- if .Values.ingress.hosts }}
      {{- $hostName = (first .Values.ingress.hosts).host }}
    {{- else }}
      {{/* Set a default or handle error if no host is defined anywhere */}}
      {{- $hostName = "gochat-default.local" }}
      {{- /* Or fail template: {{ fail "Ingress host must be defined either via ingress.hostOverride or ingress.hosts[0].host" }} */}}
    {{- end }}
  {{- end }}

  {{- /* Generate TLS section only if tlsSecretName is provided */}}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ $hostName | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}

  rules:
    - host: {{ $hostName | quote }}
      http:
        paths:
          {{- /* Always use defaultPaths */}}
          {{- range .Values.ingress.defaultPaths }}
            {{- /* Conditionally exclude /ws path if dedicated WS ingress is enabled */}}
            {{- if not (and $.Values.ingressWs.enabled (eq .path "/ws")) }}
            - path: {{ .path }}
              pathType: {{ .pathType }}
              backend:
                service:
                  # Construct service name using fullname and the serviceName from path value
                  name: {{ $fullName }}-{{ .serviceName }}
                  port:
                    # Use portName from path value
                    name: {{ .portName }}
            {{- end }}
          {{- end }}
{{- end }}