{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gochat.fullname" . -}}
{{- $svcPortApi := .Values.api.service.port -}}
{{- $svcPortWs := .Values.ws.service.port -}}
{{- $svcPortMinio := .Values.minio.service.apiPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- $hostName := .Values.ingress.hostOverride }}
  {{- if eq $hostName "" }}
    {{- if .Values.ingress.hosts }}
      {{- $hostName = (first .Values.ingress.hosts).host }}
    {{- else }}
      {{- $hostName = "gochat-default.local" }}
    {{- end }}
  {{- end }}

  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ $hostName | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}

  rules:
    - host: {{ $hostName | quote }}
      http:
        paths:
          {{- range .Values.ingress.defaultPaths }}
            {{- if not (and $.Values.ingressWs.enabled (eq .path "/ws")) }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}-{{ .serviceName }}
                port:
                  name: {{ .portName }}
            {{- end }}
          {{- end }}
          {{- if .Values.ui.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-ui
                port:
                  name: http
          {{- end }}
{{- end }}
