{{- if .Values.keydb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gochat.fullname" . }}-keydb
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: keydb
spec:
  type: {{ .Values.keydb.service.type }}
  ports:
    - port: {{ .Values.keydb.service.port }}
      targetPort: redis # Match the port name in the deployment
      protocol: TCP
      name: redis
  selector:
    {{- include "gochat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keydb
{{- end }} 