{{- if .Values.keydb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gochat.fullname" . }}-keydb
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: keydb
spec:
  replicas: {{ .Values.keydb.replicaCount }}
  selector:
    matchLabels:
      {{- include "gochat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: keydb
  template:
    metadata:
      labels:
        {{- include "gochat.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: keydb
    spec:
      containers:
        - name: keydb
          image: "{{ .Values.keydb.image.repository }}:{{ .Values.keydb.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.keydb.image.pullPolicy }}
          ports:
            - name: redis # Standard Redis/KeyDB port name
              containerPort: {{ .Values.keydb.service.port }}
              protocol: TCP
          # Add KeyDB specific args/command if needed
          # Define readiness/liveness probes for KeyDB
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
          resources:
            {{- toYaml .Values.keydb.resources | nindent 12 }}
          # Add volumeMounts if persistence is enabled
          # volumeMounts:
          #   {{- if .Values.keydb.persistence.enabled }}
          #   - name: data
          #     mountPath: {{ .Values.keydb.persistence.mountPath }}
          #   {{- end }}
      # Add volumes if persistence is enabled
      # volumes:
      #   {{- if .Values.keydb.persistence.enabled }}
      #   - name: data
      #     persistentVolumeClaim:
      #       claimName: {{ include "gochat.fullname" . }}-keydb
      #   {{- end }}
      {{- with .Values.keydb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keydb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keydb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 