{{- if .Values.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gochat.fullname" . }}-loki
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
spec:
  type: {{ .Values.loki.service.type }}
  ports:
    - port: {{ .Values.loki.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gochat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loki
{{- end }} 