{{- if and .Values.minio.enabled .Values.minioConsoleIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gochat.fullname" . }}-minio-console
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio-console-ingress
  annotations:
    {{- with .Values.minioConsoleIngress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.minioConsoleIngress.className }}
    kubernetes.io/ingress.class: {{ .Values.minioConsoleIngress.className | quote }}
    {{- end }}
spec:
  {{- if and .Values.minioConsoleIngress.tls.enabled .Values.minioConsoleIngress.tls.secretName }}
  tls:
    - hosts:
        - {{ .Values.minioConsoleIngress.host | quote }}
      secretName: {{ .Values.minioConsoleIngress.tls.secretName }}
  {{- else if and .Values.ingress.tlsSecretName }} # Fallback to main ingress TLS if console TLS not explicitly set
  tls:
    - hosts:
        - {{ .Values.minioConsoleIngress.host | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.minioConsoleIngress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix # Console runs at the root of its host
            backend:
              service:
                name: {{ include "gochat.fullname" . }}-minio
                port:
                  name: console # Target the named console port
{{- end }} 