{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gochat.fullname" . }}-nginx
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    # Uncomment if HTTPS is configured and exposed
    # - port: {{ .Values.nginx.service.httpsPort }}
    #   targetPort: https
    #   protocol: TCP
    #   name: https
  selector:
    {{- include "gochat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
{{- end }}
