{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gochat.fullname" . }}-prometheus
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |-
    {{- $fullname := include "gochat.fullname" . -}}
    {{- $promConfig := .Values.prometheus.config -}}
    {{- $scrapeConfigs := list
        (dict "job_name" "prometheus" "static_configs" (list (dict "targets" (list (printf "localhost:%d" .Values.prometheus.service.port)))))
        (dict "job_name" "gochat-api" "scrape_interval" "10s" "scrape_timeout" "5s" "metrics_path" "/metrics" "static_configs" (list (dict "targets" (list (printf "%s-%s:%d" $fullname $promConfig.apiServiceName (int $promConfig.apiServicePort))))))
        (dict "job_name" "docker" "static_configs" (list (dict "targets" (list $promConfig.dockerExporterTarget))))
    -}}
    {{- $configData := dict
        "global" (dict "scrape_interval" $promConfig.scrapeInterval "evaluation_interval" $promConfig.evaluationInterval)
        "scrape_configs" $scrapeConfigs
    -}}
    {{ $configData | toYaml | nindent 4 }}
{{- end }} 