{{- if .Values.promtail.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gochat.fullname" . }}-promtail
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: promtail
data:
  promtail-config.yml: |-
    {{- $fullname := include "gochat.fullname" . -}}
    {{- $promtailConfig := .Values.promtail.config -}}
    {{- $scrapeConfigs := list
        (dict "job_name" "kubernetes-pods"
              "kubernetes_sd_configs" (list (dict "role" "pod"))
              "pipeline_stages" (list (dict "docker" (dict)))
              "relabel_configs" (list
                  (dict "source_labels" (list "__meta_kubernetes_pod_node_name") "target_label" "__host__")
                  (dict "action" "labelmap" "regex" "__meta_kubernetes_pod_label_(.+)")
                  (dict "action" "replace" "source_labels" (list "__meta_kubernetes_namespace") "target_label" "namespace")
                  (dict "action" "replace" "source_labels" (list "__meta_kubernetes_pod_name") "target_label" "pod")
                  (dict "action" "replace" "source_labels" (list "__meta_kubernetes_pod_container_name") "target_label" "container")
                  (dict "action" "replace" "source_labels" (list "__meta_kubernetes_pod_uid" "__meta_kubernetes_pod_container_name") "target_label" "__path__" "replacement" "/var/log/pods/*$1/*.log")
              ))
    -}}
    {{- $configData := dict
        "server" (dict "http_listen_port" .Values.promtail.service.port "grpc_listen_port" 0)
        "positions" (dict "filename" $promtailConfig.positionsFilename)
        "clients" (list (dict "url" (printf "http://%s-%s:%d/loki/api/v1/push" $fullname $promtailConfig.lokiServiceName (int $promtailConfig.lokiServicePort))))
        "scrape_configs" $scrapeConfigs
    -}}
    {{ $configData | toYaml | nindent 4 }}

    # Original docker_sd_config (may work if Docker socket is mounted and accessible)
    # - job_name: containers
    #   docker_sd_configs:
    #     - host: unix://{{ .Values.promtail.config.dockerSocketPath }}
    #       refresh_interval: 5s
    #   relabel_configs:
    #     - source_labels: [ '__meta_docker_container_name' ]
    #       regex: '/(.*)'
    #       target_label: 'container'
{{- end }} 