{{- if and .Values.scylla.enabled .Values.scylla.migrate.enabled }}
{{- $fullName := include "gochat.fullname" . -}}
{{- $apiImageRepo := .Values.api.image.repository -}}
{{- $apiImageTag := .Values.api.image.tag | default .Chart.AppVersion -}}
{{- $apiImagePolicy := .Values.api.image.pullPolicy -}}
{{- $migrateImageRepo := .Values.scylla.migrate.image.repository | default $apiImageRepo -}}
{{- $migrateImageTag := .Values.scylla.migrate.image.tag | default $apiImageTag -}}
{{- $migrateImagePolicy := .Values.scylla.migrate.image.pullPolicy | default $apiImagePolicy -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-scylla-migrate
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: scylla-migrate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "{{ .Values.scylla.migrate.hookWeight | default "10" }}"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ $fullName }}-scylla-migrate
      labels:
        {{- include "gochat.labels" . | nindent 8 }}
        app.kubernetes.io/component: scylla-migrate
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-scylla
          image: busybox:latest
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for ScyllaDB service {{ $fullName }}-scylla..."
              until nc -z -w 2 "{{ $fullName }}-scylla" {{ .Values.scylla.service.cqlPort }};
              do
                echo "ScyllaDB not ready yet, sleeping...";
                sleep 2;
              done;
              echo "ScyllaDB service ready."
      containers:
        - name: scylla-migrate
          image: "{{ $migrateImageRepo }}:{{ $migrateImageTag }}"
          imagePullPolicy: {{ $migrateImagePolicy }}
          command: [
            "journey",
            "--url",
            "cassandra://{{ $fullName }}-scylla/{{ .Values.scylla.init.keyspace }}",
            "--path",
            "{{ .Values.scylla.migrate.commandPathArg | default "/db/migrations" }}",
            "migrate",
            "up"
          ]
          env:
          {{- with .Values.scylla.migrate.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: migration-files
              mountPath: "{{ .Values.scylla.migrate.migrationsPath | default "/db/migrations" }}"
      volumes:
        - name: migration-files
          configMap:
            name: {{ include "gochat.fullname" . }}-scylla-migrations
{{- end }} 