{{- if .Values.scylla.enabled }}
# Headless service for StatefulSet pod discovery
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gochat.fullname" . }}-scylla-headless
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: scylla
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: cql
      port: {{ .Values.scylla.service.cqlPort }}
      targetPort: cql
      protocol: TCP
    - name: thrift
      port: {{ .Values.scylla.service.thriftPort }}
      targetPort: thrift
      protocol: TCP
    # Add other ports like internode, JMX if needed for clustering/monitoring
  selector:
    {{- include "gochat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: scylla
---
# Regular ClusterIP service for client connections
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gochat.fullname" . }}-scylla
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: scylla
spec:
  type: {{ .Values.scylla.service.type }}
  ports:
    - name: cql
      port: {{ .Values.scylla.service.cqlPort }}
      targetPort: cql
      protocol: TCP
    - name: thrift
      port: {{ .Values.scylla.service.thriftPort }}
      targetPort: thrift
      protocol: TCP
  selector:
    {{- include "gochat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: scylla
{{- end }} 