{{- if and .Values.scylla.enabled .Values.scylla.migrate.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gochat.fullname" . }}-scylla-migrations
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: scylla-migrate-config
data:
{{ (.Files.Glob "db/migrations/*.cql").AsConfig | indent 2 }}
{{- end }} 