{{- if and $.Values.scylla.enabled $.Values.scylla.init.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gochat.fullname" . }}-scylla-init
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: scylla-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "7"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "gochat.fullname" . }}-scylla-init
      labels:
        {{- include "gochat.labels" . | nindent 8 }}
        app.kubernetes.io/component: scylla-init
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "gochat.fullname" . }}-scylla-init
      containers:
        - name: scylla-init
          image: "{{ $.Values.scylla.image.repository }}:{{ $.Values.scylla.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.scylla.image.pullPolicy }}
          command: ["/bin/bash", "-ec"]
          args:
            - |
              echo "MainContainer: Waiting 15 seconds for Scylla to stabilize..."
              sleep 15
              echo "MainContainer: Attempting to create keyspace '$SCYLLA_KEYSPACE' with RF $SCYLLA_REPLICATION_FACTOR..."
              CQL_COMMAND="CREATE KEYSPACE IF NOT EXISTS ${SCYLLA_KEYSPACE} WITH replication = {'class': 'SimpleStrategy', 'replication_factor': ${SCYLLA_REPLICATION_FACTOR}};"
              echo "MainContainer: Executing: $CQL_COMMAND on host $SCYLLA_HOST"
              retry_count=0
              max_retries=5
              until cqlsh $SCYLLA_HOST -e "$CQL_COMMAND"; do
                  retry_count=$((retry_count+1))
                  if [[ $retry_count -ge $max_retries ]]; then
                      echo "MainContainer ERROR: Failed to create keyspace using cqlsh after $max_retries attempts."
                      exit 1
                  fi
                  echo "MainContainer: cqlsh command failed, retrying in 10 seconds (${retry_count}/${max_retries})..."
                  sleep 10
              done
              echo "MainContainer: Keyspace created (or already existed)."
              echo "MainContainer: SCYLLA INIT JOB SCRIPT FINISHED Successfully"
              exit 0
          env:
            - name: SCYLLA_HOST
              value: "{{ include "gochat.fullname" . }}-scylla-headless"
            - name: SCYLLA_KEYSPACE
              value: "{{ $.Values.scylla.init.keyspace }}"
            - name: SCYLLA_REPLICATION_FACTOR
              value: "{{ $.Values.scylla.init.replicationFactor }}"
{{- end }}
