{{- if and .Values.scylla.enabled .Values.scylla.init.keyspace }} # Check if Scylla and init are enabled
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gochat.fullname" . }}-scylla-init
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: scylla-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "{{ .Values.scylla.init.hookWeight | default "5" }}" # Use value from values.yaml
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "gochat.fullname" . }}-scylla-init
      labels:
        {{- include "gochat.labels" . | nindent 8 }}
        app.kubernetes.io/component: scylla-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: scylla-init
          # Use the same Scylla image as the main deployment, as it includes cqlsh
          image: "{{ .Values.scylla.image.repository }}:{{ .Values.scylla.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.scylla.image.pullPolicy }}
          command: ["/bin/bash", "/scripts/init-scylla.sh"]
          env:
            # Pass necessary values to the script
            - name: SCYLLA_HOST
              # Use the headless service name for StatefulSet pods
              value: "{{ include "gochat.fullname" . }}-scylla-headless"
            - name: SCYLLA_KEYSPACE
              value: "{{ .Values.scylla.init.keyspace }}"
            - name: SCYLLA_REPLICATION_FACTOR
              value: "{{ .Values.scylla.init.replicationFactor }}"
            # Add SCYLLA_USER/PASSWORD if authentication is enabled
            # - name: SCYLLA_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ include "gochat.fullname" . }}-scylla
            #       key: username
            # - name: SCYLLA_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ include "gochat.fullname" . }}-scylla
            #       key: password
          volumeMounts:
            - name: init-script
              mountPath: /scripts
      volumes:
        - name: init-script
          configMap:
            # Ensure this ConfigMap contains the init-scylla.sh script
            name: {{ include "gochat.fullname" . }}-scylla-init-script
            defaultMode: 0755 # Make script executable
{{- end }}
