{{- define "gochat.secrets" -}}
{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gochat.fullname" . }}-minio
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.minio.auth.rootUser | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.auth.rootPassword | b64enc | quote }}
---
{{- end }}
{{- /* Add other secrets here as needed */ -}}
{{- end -}}

{{- template "gochat.secrets" . -}} 