{{- if .Values.solr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gochat.fullname" . }}-solr-headless
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: solr
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.solr.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "gochat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: solr
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gochat.fullname" . }}-solr
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: solr
spec:
  type: {{ .Values.solr.service.type }}
  ports:
    - name: http
      port: {{ .Values.solr.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "gochat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: solr
{{- end }}