{{- if $.Values.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gochat.fullname" . }}-ui
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ $.Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "gochat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gochat.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gochat.serviceAccountName" . }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-ui
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.ui.image.repository }}:{{ $.Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.ui.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "gochat.fullname" . }}-ui
          ports:
            - name: http
              containerPort: {{ $.Values.ui.config.port }}
              protocol: TCP
          {{- if $.Values.ui.resources }}
          resources:
            {{- toYaml $.Values.ui.resources | nindent 12 }}
          {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 