{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gochat.fullname" . }}-ui
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http # Corresponds to the container port name in the deployment
      protocol: TCP
      name: http
  selector:
    {{- include "gochat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
{{- end }} 