{{- if .Values.ws.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gochat.fullname" . }}-ws
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
    app.kubernetes.io/component: ws
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "15"
spec:
  replicas: {{ .Values.ws.replicaCount }}
  selector:
    matchLabels:
      {{- include "gochat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ws
  template:
    metadata:
      labels:
        {{- include "gochat.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ws
    spec:
      containers:
        - name: ws
          image: "{{ .Values.ws.image.repository }}:{{ .Values.ws.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ws.image.pullPolicy }}
          ports:
            - name: ws
              containerPort: {{ .Values.ws.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /dist/config.yaml
              subPath: config.yaml
          resources:
            {{- toYaml .Values.ws.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "gochat.fullname" . }}-ws
            items:
              - key: config.yaml
                path: config.yaml
      {{- with .Values.ws.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ws.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ws.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 