/*
GoChat API

Testing AvatarsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package goclient

import (
	"context"
	openapiclient "github.com/FlameInTheDark/gochat/clients/api/goclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_goclient_AvatarsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AvatarsAPIService AvatarsUserIdAvatarIdPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var userId int32
		var avatarId int32

		resp, httpRes, err := apiClient.AvatarsAPI.AvatarsUserIdAvatarIdPost(context.Background(), userId, avatarId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
