/*
GoChat API

Testing EmojiAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package goclient

import (
	"context"
	openapiclient "github.com/FlameInTheDark/gochat/clients/api/goclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_goclient_EmojiAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EmojiAPIService EmojiEmojiIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var emojiId string

		httpRes, err := apiClient.EmojiAPI.EmojiEmojiIdGet(context.Background(), emojiId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmojiAPIService InfoEmojiEmojiIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var emojiId int32

		resp, httpRes, err := apiClient.EmojiAPI.InfoEmojiEmojiIdGet(context.Background(), emojiId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
