name: Build Release Images

# Trigger when a release is published
on:
  release:
    types: [published]

permissions:
  contents: read # Only read access required to checkout code
  packages: write # Needed to push container images to GHCR

jobs:
  build-images:
    name: Build and Push Container Images
    runs-on: ubuntu-latest
    steps:
      # Checkout the specific tag associated with the release
      - name: Check out code at specific tag
        uses: actions/checkout@v4
        with:
          # github.ref is the tag name for release events (e.g., refs/tags/v1.0.0)
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Uses the workflow's GITHUB_TOKEN

      - name: Extract metadata for API image
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/gochat-api
          tags: |
            type=ref,event=tag
            # Always tag as latest on release
            type=raw,value=latest,enable=true

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the repository root
          file: ./api.Dockerfile # Dockerfile is in the root
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for WS image
        id: meta_ws
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/gochat-ws
          tags: |
            type=ref,event=tag
            # Always tag as latest on release
            type=raw,value=latest,enable=true

      - name: Build and push WS image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the repository root
          file: ./ws.Dockerfile # Dockerfile is in the root
          push: true
          tags: ${{ steps.meta_ws.outputs.tags }}
          labels: ${{ steps.meta_ws.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for AUTH image
        id: meta_auth
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/gochat-auth
          tags: |
            type=ref,event=tag
            # Always tag as latest on release
            type=raw,value=latest,enable=true

      - name: Build and push AUTH image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./auth.Dockerfile
          push: true
          tags: ${{ steps.meta_auth.outputs.tags }}
          labels: ${{ steps.meta_auth.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for INDEXER image
        id: meta_indexer
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/gochat-indexer
          tags: |
            type=ref,event=tag
            # Always tag as latest on release
            type=raw,value=latest,enable=true

      - name: Build and push INDEXER image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./indexer.Dockerfile
          push: true
          tags: ${{ steps.meta_indexer.outputs.tags }}
          labels: ${{ steps.meta_indexer.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for ATTACHMENTS image
        id: meta_attachments
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/gochat-attachments
          tags: |
            type=ref,event=tag
            # Always tag as latest on release
            type=raw,value=latest,enable=true

      - name: Build and push ATTACHMENTS image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./attachments.Dockerfile
          push: true
          tags: ${{ steps.meta_attachments.outputs.tags }}
          labels: ${{ steps.meta_attachments.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for WEBHOOK image
        id: meta_webhook
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/gochat-webhook
          tags: |
            type=ref,event=tag
            # Always tag as latest on release
            type=raw,value=latest,enable=true

      - name: Build and push WEBHOOK image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./webhook.Dockerfile
          push: true
          tags: ${{ steps.meta_webhook.outputs.tags }}
          labels: ${{ steps.meta_webhook.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for SFU image
        id: meta_sfu
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/gochat-sfu
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=true

      - name: Build and push SFU image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./sfu.Dockerfile
          push: true
          tags: ${{ steps.meta_sfu.outputs.tags }}
          labels: ${{ steps.meta_sfu.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-binaries:
    name: Build and Upload Release Binaries
    runs-on: ubuntu-latest
    needs: build-images
    steps:
      - name: Check out code at tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Build SFU and Tools binaries (linux/amd64)
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
        run: |
          mkdir -p dist
          go build -o dist/sfu_linux_amd64 ./cmd/sfu
          go build -o dist/gctools_linux_amd64 ./cmd/tools

      - name: Build SFU and Tools binaries (linux/arm64)
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: arm64
        run: |
          go build -o dist/sfu_linux_arm64 ./cmd/sfu
          go build -o dist/gctools_linux_arm64 ./cmd/tools

      - name: Create checksums
        run: |
          cd dist
          sha256sum * > SHA256SUMS.txt

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/sfu_linux_amd64
            dist/sfu_linux_arm64
            dist/gctools_linux_amd64
            dist/gctools_linux_arm64
            dist/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
