name: Semantic Release Installer

# Trigger the workflow on pushes to branches matching main
on:
  push:
    branches:
      - main # Trigger on push to main

permissions:
  contents: write # To push tags/commits, create releases, upload assets
  issues: write   # Optional: semantic-release can comment on issues/PRs
  pull-requests: write # Optional: semantic-release can comment on issues/PRs

jobs:
  release:
    name: Semantic Release and Build
    runs-on: ubuntu-latest
    # Prevent duplicate runs for pushes that include multiple commits
    concurrency: ${{ github.workflow }}-${{ github.ref }}

    outputs: # Define outputs for other jobs if needed
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      # 1. Checkout code
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # Fetch all history so semantic-release can analyze commits
          fetch-depth: 0
          # Persist credentials needed for the push-back step by semantic-release/git
          persist-credentials: false

      # 2. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Use LTS Node version

      # 3. Install semantic-release and plugins
      # Committing package.json with these as devDeps is recommended
      - name: Install semantic-release plugins
        run: |
          npm install -D \
            semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/github

      # 4. Run semantic-release
      - name: Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Run semantic-release and capture outputs
        run: npx semantic-release
        # Continue workflow even if semantic-release determines no release is needed
        continue-on-error: true

      # Check outputs from semantic-release (these might vary slightly by version/plugins)
      - name: Debug semantic release outputs
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "New release published: ${{ steps.semantic.outputs.new_release_published }}"
          echo "New release version: ${{ steps.semantic.outputs.new_release_version }}"
          echo "New release tag: ${{ steps.semantic.outputs.new_release_git_tag }}"

      # --- Build and Upload only if a new release was created ---

      - name: Set up Go
        if: steps.semantic.outputs.new_release_git_tag # Check if tag was generated
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Specify your Go version

      - name: Build Go Binaries (Cross-Platform)
        if: steps.semantic.outputs.new_release_git_tag # Check if tag was generated
        id: build
        run: |
          set -e # Exit on error
          # Define targets (OS/Arch)
          targets=(
            "linux/amd64"
            "linux/arm64"
            "windows/amd64"
            "darwin/amd64"
            "darwin/arm64"
          )

          INSTALLER_DIR="cmd/installer" # Path to the installer code
          OUTPUT_DIR="release_builds"   # Temporary directory for builds
          mkdir -p ${OUTPUT_DIR}

          for target in "${targets[@]}"; do
            IFS='/' read -r os arch <<< "$target"
            output_name="installer-${os}-${arch}"
            if [ "$os" = "windows" ]; then
              output_name+=".exe"
            fi

            echo "Building for $os/$arch -> ${OUTPUT_DIR}/${output_name}"
            GOOS=$os GOARCH=$arch go build -ldflags="-s -w" -o "${OUTPUT_DIR}/${output_name}" "${INSTALLER_DIR}/main.go"
          done

          # List built files
          ls -R ${OUTPUT_DIR}

      - name: Upload Release Assets using gh CLI
        if: steps.semantic.outputs.new_release_git_tag # Check if tag was generated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Get the tag name from semantic-release outputs
          RELEASE_TAG: ${{ steps.semantic.outputs.new_release_git_tag }}
        run: |
          echo "Uploading assets for tag: $RELEASE_TAG"
          if [ -z "$RELEASE_TAG" ]; then
            echo "Error: Release tag not found from semantic-release step."
            exit 1
          fi
          gh release upload "$RELEASE_TAG" release_builds/* --clobber
