name: Semantic Release

# Trigger the workflow on pushes to branches matching main
on:
  push:
    branches:
      - main # Trigger on push to main

permissions:
  contents: write # To push tags/commits, create releases
  issues: write   # Optional: semantic-release can comment on issues/PRs
  pull-requests: write # Optional: semantic-release can comment on issues/PRs

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    # Prevent duplicate runs for pushes that include multiple commits
    concurrency: ${{ github.workflow }}-${{ github.ref }}

    steps:
      # 1. Checkout code
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # Fetch all history so semantic-release can analyze commits
          fetch-depth: 0
          # Persist credentials needed for the push-back step by semantic-release/git
          persist-credentials: false

      # 2. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Use LTS Node version

      # 3. Install semantic-release and plugins
      # Committing package.json with these as devDeps is recommended
      - name: Install semantic-release plugins
        run: |
          npm install -D \
            semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/github

      # 4. Run semantic-release
      - name: Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Run semantic-release and capture outputs
        run: npx semantic-release
        # Continue workflow even if semantic-release determines no release is needed
        continue-on-error: true

      # Check outputs from semantic-release (these might vary slightly by version/plugins)
      - name: Debug semantic-release step outputs
        if: always() # Always run this step
        run: echo "${{ toJSON(steps.semantic.outputs) }}"
